### ISSUE TITLE
Iterate 2-month call 2 agenda

### ISSUE THREAD

**Issue by jules32** [Openscapes/how_we_work#1]
Hi @erinmr, how does this [02_CallAgenda](https://docs.google.com/document/d/15Z-INAStgfo4q2kLSYGPzP5Y3nkI4HlAihHsNMlEAzg/edit#) timing look for Friday?

**Comment by jules32** [comment]
@erinmr I also iterated <https://openscapes.github.io/series/index.html#agendas>

**Comment by erinmr** [comment]
i think this looks super 👍

**Comment by jules32** [comment]
Great, thanks
