### ISSUE TITLE
Digest for Mentor Cohort 06

### ISSUE THREAD

**Issue by jules32** [Openscapes/how_we_work#10]
Be sure to highlight

- [x] June 30 push, Jupyterbook, [outline](https://docs.google.com/document/d/12uEPP_w4M4SMrLkcVzUwX7htWtTzlS5a3ahJnK7fSAs/edit)
- [x] Pathways next week
- [x] openscapes.org/Champions, dates. 

anything else @erinmr ?

**Comment by jules32** [comment]
not sure that tagged you bc I edited a comment. We'll test it @erinmr

**Comment by erinmr** [comment]
The first one did tag me 👍  If anyone wants to experiment with 2i2c we are open to that too and would love to share a few examples on our June 10 session.

**Comment by jules32** [comment]
Posted https://github.com/NASA-Openscapes/mentors-2021/issues/25
