### ISSUE TITLE
open science video (<4 min) for Eli

### ISSUE THREAD

**Issue by jules32** [Openscapes/how_we_work#102]
Hi @erinmr,

Not pressing but here's a [draft 4-min video](https://drive.google.com/file/d/12J3O31x5coGi95e5dkVbkfmAyM93C80H/view?usp=sharing) for Eli, showing off some of our open science work with NASA. It's a lot but trying to give a broad sense and be concrete of what's possible, collaboration, etc. 

Happy to iterate (or share imperfect as is) if we think this sort of thing would be useful for our December talks or for the mentors. If I do iterate I'd like to figure out how to make time to show the full quarto book, so ideas of what to cut or streamline are welcome :)

**Comment by erinmr** [comment]
I could not love this more. It has so much great stuff in it. Great work!

**Comment by jules32** [comment]
sent to eli with logo added. will share link here when it's up
