### ISSUE TITLE
NASA agenda & hackathon feedback review

### ISSUE THREAD

**Issue by jules32** [Openscapes/how_we_work#109]

**Comment by jules32** [comment]
Hi @erinmr , I've got a rough outline of the [mentors working agenda ](https://docs.google.com/document/d/1eRoZnSqUCmPALHnQnWLU_BiPJjcGhAtcvlO4rArGW6A/edit#) if you'd like to review; then we can Slack the Mentors to see if they have edits ahead of time. I'll join 20 mins late on Thursday (rather than ducking out).

**Comment by erinmr** [comment]
Looks good to me
