### ISSUE TITLE
ESIP open community 15-min talk

### ISSUE THREAD

**Issue by jules32** [Openscapes/how_we_work#113]
10-minute talk on Openscapes in the January 2022 ESIP meeting session: “Community Development for Open Science”. The session will be held on Tuesday, January 18 from 1:30pm - 3:00pm ET. The session will include 6 10-minute “lighting” talks followed by 30 minutes of general discussion.

**Comment by jules32** [comment]
A working draft of our slides with quarto, migrated to openscapes' github: 

<https://openscapes.github.io/slides/esip_winter2022>

There are 21 slides (including title and closing slides) so we'll have to cut but something to work with! Feel free to iterate or we can do it together on Monday @erinmr

**Comment by erinmr** [comment]
I think we can make it through with what's here. We can talk about any
tweaks on Monday.
