### ISSUE TITLE
newsletter - march

### ISSUE THREAD

**Issue by jules32** [Openscapes/how_we_work#133]
Draft newsletter for March. Include: 

- Open call announcement
- ESIP blog
- NASA Champions kickoff
- link to NASA progress report

**Comment by jules32** [comment]
- BSSw Fellow

**Comment by erinmr** [comment]
This looks great! 🌹 🌷

**Comment by jules32** [comment]
Awesome, thanks Erin ❤️

**Comment by jules32** [comment]
Sent!
