### ISSUE TITLE
website tags re-think

### ISSUE THREAD

**Issue by jules32** [Openscapes/how_we_work#143]
we'd like these:
- [x] newsletter
- [ ] champions cohorts
- [x] NOAA, NASA

events page

- [x] remove "event completed"

**Comment by stefaniebutland** [comment]
We now have 
https://www.openscapes.org/tags/noaa-fisheries/

https://www.openscapes.org/tags/nasa-framework/

https://www.openscapes.org/tags/newsletter/

**Comment by jules32** [comment]
This is so great, thanks! Soon after our co-working tomorrow we'll be able to check the "remove events completed" box. 

the champions cohorts tag is a definite "nice to have" that maybe we can tackle when pursuing the "tl;dr's"

**Comment by stefaniebutland** [comment]
Closing this, as we've settled it for website-new
