### ISSUE TITLE
Social Hour planning

### ISSUE THREAD

**Issue by jules32** [Openscapes/how_we_work#144]
Hi @stefaniebutland!

**Comment by stefaniebutland** [comment]
**The idea**: Monthly social hour May - Aug 2022. Engage Champions after their Cohorts end and include Mentors and others in the Openscapes Slack. Start with a virtual social hour to ease folks into getting to know people from other Cohorts. Strengthen connections within and across cohorts. These would be social and opportunities for cross-learning but not anything to prepare for ahead of time. 

Stef to lead this.

- [ ] Stef & Julie draft plan
- [ ] share [doc](https://docs.google.com/document/d/1-xCGlhlUV5iNUAaXxfewV2IFzrcBZPnLD3Ea_n4pTe0/edit#) with Ileana, Eli, Allison to get feedback by Apr 25
- [ ] set a May date/time (do we need to poll for this?)
- [ ] announce plan on Slack
- [ ] do the thing
- [ ] capture success stories or challenges in notes; fodder for blog post, or use cases to add to lesson series? capture # of people attending from which cohorts or mentors groups
- [ ] post a "we did this thing" in Slack to encourage folks to attend next time
- [ ] select June date
- [ ] repeat monthly May - Aug 2022
- [ ] evaluate and report on success; would we do it again; changes to make

Consider how to evaluate; what does success look like
- numbers of attendees each session
- do people follow up with each other after a session?
- do we do a short assessment form after August session?

**Comment by stefaniebutland** [comment]
Tentative time: Monday, May 16, 1-1:50pm PT (UTC-7)

Ileana, Allison, Eli all available!

**Comment by jules32** [comment]
Yay! Excited for this @stefaniebutland !
