### ISSUE TITLE
Add Quarto keynote to events page

### ISSUE THREAD

**Issue by jules32** [Openscapes/how_we_work#149]
- [x] quarto keynote
- [x] community call quarto

**Comment by stefaniebutland** [comment]
Added in this PR https://github.com/Openscapes/events/pull/10.

banner image is 520x520, but in the events list page, it appears to take up extra vertical space 🤔

**Comment by jules32** [comment]
Closing following merging Stef's PR https://github.com/Openscapes/events/pull/10
