### ISSUE TITLE
migrate events page > quarto

### ISSUE THREAD

**Issue by jules32** [Openscapes/how_we_work#150]
Earlier in April I made a branch and the first steps at migrating the events page from distill to quarto. This is not a huge priority but I wanted to document it here to pick up and complete it. I think that 1-2 hours of co-working might be all we need to finish doing so, especially having read Danielle Navarro's blog post https://blog.djnavarro.net/posts/2022-04-20_porting-to-quarto/. cc'ing @stefaniebutland if there's a week that time-wise makes sense to schedule an hour together to just go for it!

Current status: 

- branch with migration: https://github.com/openscapes/events/tree/quarto-convert. 
- have to render from terminal `quarto render` because RStudio IDE still thinks it's distill, see next steps

Next steps: 
- [x] update color scheme/css
- [x] remove first 2 fake blog posts
- [x] migrate the thumbnails so they also show up in the post
- [x] Remove anything else that RStudio is still thinking as distill (right now the "build" tab still says "build website" and errors bc it's looking for RMarkdown)
- [x] make sure top navbar stays put when scrolling
- [x] make sure SEFSC exists

What it looks like now: 

<img width="1409" alt="image" src="https://user-images.githubusercontent.com/5891909/165858970-3b0a2c30-90c4-48e0-8254-d0dbfffbdc01.png">

**Comment by stefaniebutland** [comment]
> cc'ing @stefaniebutland if there's a week that time-wise makes sense to schedule an hour together to just go for it!

Weeks of May 2, 9, or 16 are good for me.

**Comment by stefaniebutland** [comment]
Stef & Julie coworked on this May 5.

- Stef will start by making thumbnails appear in the blog listing page, remove tags `event completed` and ping Julie for next step when that's done.
- we'll need to add back ` /styles.css` somewhere (404: Not Found)

**Comment by stefaniebutland** [comment]
In the Quarto previews, for posts that have a TOC in the live Events page, TOC does not appear. 
I left the distill bit in these for now.
- /posts/2021-09-17-fdd/ 
- /posts/2021-09-17-nwfsc/

**Comment by stefaniebutland** [comment]
See [Danielle Navarro's post ](https://blog.djnavarro.net/posts/2022-04-20_porting-to-quarto/) to fix TOC and Citations.
"Specifying the table of contents is slightly different..."
"One feature in distill that I like is that it generates a citation for each post..."

**Comment by stefaniebutland** [comment]
- [ ] restore citations
- [ ] restore footer
- [ ] define TOC
- [ ] update README


Nice to have or need to have?
- [ ] rename files.Rmd to files.qmd (code in [Nick Tierney's post](https://www.njtierney.com/post/2022/04/11/rmd-to-qmd/))

**Comment by stefaniebutland** [comment]
Notes on  adding citations [SHA](https://github.com/Openscapes/events/commit/fd3517b403df6087fe1242a82b1ecb1e48096cd7) 
- [ ] added `citation: true` to `_metadata.yml` to have citation in all posts
- [ ] fixed date error in Duckles post citation was by changing to ISO date format in post (noted in Danielle's post). 
- [ ] Change date format to ISO in every post.
- [ ] Restore `Retrieved from ...URL` to citations. Maybe by setting `site-url` (Base URL for published website) under the `website` key in `_quarto.yml` noted in [Quarto docs](https://quarto.org/docs/reference/projects/websites.html#meta-project-type-upper)

Quarto docs citation example:
<img width="1066" alt="Screen Shot 2022-05-06 at 2 12 35 PM" src="https://user-images.githubusercontent.com/11927811/167219906-d638e565-7e5c-4186-a209-ef5a7f9c39d3.png">

Preview of Beth's post
<img width="814" alt="Screen Shot 2022-05-06 at 2 15 38 PM" src="https://user-images.githubusercontent.com/11927811/167219910-565d7158-cfce-4ec5-9fff-605b799618fe.png">

**Comment by jules32** [comment]
Woohoo nice job @stefaniebutland look at our nice events **quarto** site! 

I wrote up a few notes about distill here - feel free to add any other thoughts. https://openscapes.github.io/quarto-website-tutorial/transition-from-rmarkdown.html#distill-to-quarto


<img width="1210" alt="image" src="https://user-images.githubusercontent.com/5891909/167730610-40104e8e-de16-41a8-b54f-c0533037c4cf.png">

**Comment by stefaniebutland** [comment]
Need a redirect ?
https://openscapes.github.io/events 

Link in citation for a post gives 404:
`Openscapes. 2022. “A Qualitative Data Analysis Chat with Beth Duckles.” April 8, 2022. https://openscapes.org/posts/2022-04-08-qda-beth-duckles.`

**Comment by jules32** [comment]
Ah yes, I think this is because it should be openscapes.github.io listed in the `_quarto.yml`; we have it redirect only for openscapes.org/events but not for any specific posts from there

**Comment by jules32** [comment]
OK @stefaniebutland I've fixed this redirect issue by having the correct `site-url: https://openscapes.github.io/events`: ([commit](https://github.com/Openscapes/events/commit/ec94356a10ccfa4a0b09282a1bd173a1ffe6b193#diff-469a07f57393912a9c17c3ea50ceebe991e32b008beb167a200b17e91fdac6d2))

**Comment by jules32** [comment]
And I've fixed the strange issue of the body text showing upby updating the `description` field (instead of `subtitle` as it was in distill:  ([commit](https://github.com/Openscapes/events/commit/ec94356a10ccfa4a0b09282a1bd173a1ffe6b193#diff-524396085dd5c28a46572882d11bc0bbc4b0086fa3046f2e68957a777e0a6936))


<img width="724" alt="Screen Shot 2022-05-10 at 6 35 37 PM" src="https://user-images.githubusercontent.com/5891909/167756715-40e11a47-f5b9-45fd-b8eb-d0ecd55cc92c.png">

**Comment by jules32** [comment]
Hi @stefaniebutland, I've updated the way that we publish the events page, using GitHub Actions and updating our `.gitignore` after talking to Mine Cetinkaya-Rundel. I've written up notes here as a start, and we can refine them when we do it again (with screenshots, etc): 
https://openscapes.github.io/quarto-website-tutorial/transition-from-rmarkdown.html#distill-to-quarto. 

See what you think, and then let's close this issue! woooo

**Comment by stefaniebutland** [comment]
Hi @jules32, I added some notes in [this PR](https://github.com/Openscapes/quarto-website-tutorial/pull/2) and proposed Events README update in [this PR ](https://github.com/Openscapes/events/pull/8).

Once you've requested or made edits and merged _then_ we're good to close the issue. Woooooo indeed!

**Comment by jules32** [comment]
Reviewed and merged! 🥳
