### ISSUE TITLE
Pathways Chapter

### ISSUE THREAD

**Issue by jules32** [Openscapes/how_we_work#151]
**Also update the Agenda kyber templates:** 
- [x] Tie to reflections breakout groups. 
- [x] Add link/guidance to the first Pathways intro and tasks (call 1, 4)

See notes from NASA Champions debrief for more

**Comment by jules32** [comment]
The beginning of the Pathways chapter is here: https://openscapes.github.io/series/core-lessons/pathways.html. 

I have the following TODO's, cc'ing @erinmr for other ideas/feedback
- [ ] build out first section maybe rename, link to Pathways doc and screenshot
- [ ] add examples: 
  - [ ] EcoFOCI
  - [ ] Cohort 1 Case Study blogs
  - [ ] ...

**Comment by jules32** [comment]
- [ ] Reflections: this is your time. Reflect on what you've learned, say things out loud, meet your colleagues

**Comment by erinmr** [comment]
This chapter looks great. I'm excited for the addition of examples and I
like the questions as another way to think about what to present.

**Comment by jules32** [comment]
Updated, see [series commit](https://github.com/Openscapes/series/commit/66be1d9dd574fdb80fdc95c398ab80d97222806a) and [kyber PR](https://github.com/Openscapes/kyber/pull/22)

**Comment by jules32** [comment]
Made additional edits here, tying into welcome page and better science chapter (since in SEFSC we have a guest better science share and don't introduce creating space/place and finding the common) including adding the pathways image in the margin 😎 

https://github.com/Openscapes/series/pull/11
