### ISSUE TITLE
add kyber to approach guide

### ISSUE THREAD

**Issue by jules32** [Openscapes/how_we_work#159]
As Sean works on the Roadmap (see https://github.com/Openscapes/kyber/issues/20)

**Comment by jules32** [comment]
Made this progress for Monday with Anna, Corey, and Stef - 

https://github.com/Openscapes/approach-guide/pull/21

Discussed with Sean about so we can interface between Approach Guide and openscapes.github.io/kyber packagedown website!

**Comment by stefaniebutland** [comment]
kyber notes added to [Approach Guide](https://openscapes.github.io/approach-guide/champions/pre-cohort-tech.html) and some how-to in [kyber README](https://github.com/Openscapes/kyber/blob/main/README.md)

**Comment by jules32** [comment]
And updated following NMFS Fall cohorts
