### ISSUE TITLE
Fix quarto-deploy-and-render GitHub Action error

### ISSUE THREAD

**Issue by stefaniebutland** [Openscapes/how_we_work#183]
Observations

* quarto-render-and-deploy GHA gave same errors for deploy of both quarto books [Approach Guide](https://github.com/Openscapes/approach-guide/runs/7057204443?check_suite_focus=true) and [Lesson Series](https://github.com/Openscapes/series/runs/7033347947?check_suite_focus=true): 
    * `Error: Can't find 'action.yml', 'action.yaml' or 'Dockerfile' under '/home/runner/work/_actions/quarto-dev/quarto-actions/main/install-quarto'. Did you forget to run actions/checkout before running your local action?`
    * Looks like the problem is with quarto-dev actions setup
    * “This repository stores Github Actions useful for building and publishing Quarto documents”:  https://github.com/quarto-dev/quarto-actions
* See resources recommended by David Keyes & Maëlle Salmon [https://twitter.com/dgkeyes/status/1541830773321347072](https://twitter.com/dgkeyes/status/1541830773321347072) 
* I triggered re-run of failed actions but it failed again
* These pages show history of successful & failed Actions in our books
    * [https://github.com/Openscapes/approach-guide/actions](https://github.com/Openscapes/approach-guide/actions)
    * [https://github.com/Openscapes/series/actions](https://github.com/Openscapes/series/actions)

**Comment by stefaniebutland** [comment]
We might need to update documentation in https://openscapes.github.io/quarto-website-tutorial/explore.html#setup-github-action

**Comment by stefaniebutland** [comment]
And check if we need to update Faylab manual GHA: https://github.com/Openscapes/lab-manual/issues/1#issuecomment-1169378419

**Comment by jules32** [comment]
This is fixed with pointing to @v1  in uses of the GitHub Action: [example](https://github.com/Openscapes/series/commit/932e4dd00538c7604ac9d0108ebf354c93223489).

The fix follows my note to Quarto team: 

> our GitHub Actions for Quarto have failed in the last day or so and I'm not sure what to update on our side. Would you be able to have a look? Here is our first [build fail](https://github.com/Openscapes/approach-guide/runs/7057204443?check_suite_focus=true#step:1:38), and our [quarto-render.yml](https://github.com/Openscapes/approach-guide/commits/main/.github/workflows/quarto-render.yml) files before & current to the build fail and my attempt to update with [quarto-publish-example.yml](https://github.com/quarto-dev/quarto-actions/blob/main/examples/quarto-publish-example.yml)

Christophe said: 
> Old action file is failing because we updated the repo and you were using main for the action. If you point to @v1  in uses the old action should still be available
> In the newer attemp, (https://github.com/Openscapes/approach-guide/actions/runs/2583243421) I think you just have an indentation issue in the YAML. 
- Julie note: this is good to know because the GA didn't even attempt to run here, so when that happens the first idea should be to look for indentation errors in the yaml
