### ISSUE TITLE
Community call idea: open science for the climate movement

### ISSUE THREAD

**Issue by stefaniebutland** [Openscapes/how_we_work#190]
Idea is to build on @jules32's rstudio::conf keynote call to action to reimagine open science as part of the climate movement by introducing the idea, give concrete examples of how people are doing this today, and provide initial ideas on how others can get involved. In shared notes, could invite folks to note things they are doing / involved in; things they are wanting to get involved in; things that are missing.

Idea spurred by @Monsauce's Aug 30 tweets:
> I'm so proud that I get to lead this initiative at creativecommons. As a champion of open knowledge and a trained ecologist, there is no more important challenge I could be working on.
https://twitter.com/Monsauce/status/1564651569928339458?s=20&t=S8dLZYdOonsVdt0PkWP0fg

https://twitter.com/Monsauce/status/1564667226409652224?s=20&t=S8dLZYdOonsVdt0PkWP0fg
<img width="650" alt="Screen Shot 2022-08-31 at 10 27 21 AM" src="https://user-images.githubusercontent.com/11927811/187741644-342ddcf9-a6ff-4e91-a366-f3d1a1054fc8.png">

aside: I understand that Openscapes is not explicitly training/promoting open access, but Monica's tweet triggered the thought that there are people in important places doing these things who "get" what Openscapes is doing from both the environmental science and open science sides because of their training. Openscapes Champion, Martin Jean has worked with Monica at Environment and Climate Change Canada -> network.

**Comment by jules32** [comment]
This would be so great! And H/t Monica: This year's Open Access week theme is Climate Justice: https://www.openaccessweek.org/ October 24 - 30, 2022

**Comment by stefaniebutland** [comment]
- What can I do to contribute to the climate crisis?
- 1 hour: 5 min intro 
- 25 min celebrity interview 
  - “Open science as a daily habit” - framing off RStudio keynote
    - Eg blogs, twitter
  - Open access vs open science
  - Making actionable concrete recs/example. What’s missing
  - Qs:
    - Please define open access and how it plays into open as a daily practice
- 25 min discussion 
  - silent journaling - what things have you been involved in that are relevant or what are your ideas

**Comment by stefaniebutland** [comment]
Monica's confirmed for Dec 1, and Nov 17 pre-event planning meeting 🎉

**Comment by stefaniebutland** [comment]
> We underestimate the power of contribution--of acting within our own sphere of influence to tackle the piece of the problem that is right in front of us.

Litigating in a Time of Crisis, by Abigail Dillen in All We Can Save

**Comment by jules32** [comment]
Amazing quote!

**Comment by stefaniebutland** [comment]
## Resources we want to share 
#### please edit this comment to add any resources we want to share on the Event page and/ or in the collaborative notes doc for the Community Call

- Julie's rstudio::conf keynote ([summary blog post](https://www.openscapes.org/blog/2022/08/10/quarto-keynote/)) with call to action to reimagine open science as part of the climate movement
- [The All We Can Save Project](https://www.allwecansave.earth/) with book and building community around solutions via circles
  - "All We Can Save is a bestselling anthology of writings by 60 women at the forefront of the climate movement who are harnessing truth, courage, and solutions to lead humanity forward."

**Comment by stefaniebutland** [comment]
Event page, w registration link: [Open Science for the Climate Movement, a chat with Monica Granados](https://openscapes.github.io/events/posts/2022-12-01-open-climate-movement-monica-granados/)

[Tweet to share](https://twitter.com/openscapes/status/1580233889888743424)

**Comment by stefaniebutland** [comment]
Notes from Julie's part of [keynote](https://www.youtube.com/watch?v=p7Hxu4coDl8) starting ~min 50, mostly quoted. 

Reimagining open science as part of the climate movement. We already know what the R and open science and open source communities are capable of. So what if we put that energy towards climate?

"We need every solution and every solver" authors of All We Can Save across all facets of geography, skill levels, experience with technology.

3 user groups:

1. scientists working directly with climate change 
  - e.g. fisheries scientists studying where are food sources are migrating to as the oceans warm
  - These are big problems but they can feel stuck on "little problems" like moving files around and interoperating with each other. Openscapes was born of this and connecting these people with each other
2. open science and R communities
  - changing to more efficient lightbulbs isn't enough. What if you aligned your daily work as part climate action as well?
3. ?

This requires slowing down to speed up.

Culture shifts: technical + human. We've got the tech side well figured out. Bring that power and energy to the human side.

Think about the teams & colleagues you interact with. Talk to your them. How are they doing? Are they stuck? Where is their friction? Who is contributing to our workflow? How are the handoffs between reports or data? What can we do to help?

Often we don't have language to describe where we're stuck and that's part of the problem. Step up. Be braver. Say what you need. It's a practice to develop daily.

Example 1: Faylab lab manual created together during the pandemic. (open, living, imperfect -> radical in science)

- Make the implicit explicit
- Onboard learners as contributors
- Psychological safety and growth mindset

The power of yet: "I don't know this ... yet".

Quarto for culture change: Faylab manual, NASA Earthdata cookbook, Openscapes Approach Guide.

**Comment by jules32** [comment]
Yayyyy that was so fun, thank you Monica! Thank you Stef! Wish we could talk for hours more!

I've now made the doc view-only for everyone besides us

**Comment by jules32** [comment]
[Our google doc](https://docs.google.com/document/d/1iz0UrhK8_5P0MkiqwEBBaW1fzbhFxN_UF8I4c4dE1OA/edit?usp=share_link
)

**Comment by jules32** [comment]
Blog post posted! Woo thanks Stef and Monica!

https://www.openscapes.org/blog/2022/12/20/monica-granados/
