### ISSUE TITLE
Create issue templates for CohortPlanning GitHub project

### ISSUE THREAD

**Issue by stefaniebutland** [Openscapes/how_we_work#193]
We're **experimenting** with using GitHub issue templates.

## Why
Tasks for 4 Fall cohorts are checklists in multiple issues in our [CohortPlanning GitHub project](https://github.com/orgs/Openscapes/projects/7/views/7). Each issue is repeated 4 times, once for each cohort. Would be nice to have one template for each issue. Issue template contains the up to date checklist. The issue template can be updated and used for future Champions Cohorts. Good for efficient execution of repeated tasks, and for (potential) onboarding of new facilitators e.g. Anna & Corey's current Cohort.

## How to use our issue templates with our GitHub Project

GitHub's [How to create an issue template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository)

Issues for our CohortPlanning GitHub project live in https://github.com/Openscapes/cohort-planning, so that's where the issue template lives. **From the [Openscapes/cohort-planning](https://github.com/Openscapes/cohort-planning) repo page, open a new issue and we're presented with the choice to use the template (click Get started; screenshot) or open a blank issue.**

Challenge: I cannot see how to create an issue from template when starting from the GitHub Project page. 

![Screen Shot 2022-09-12 at 4 37 33 PM](https://user-images.githubusercontent.com/11927811/189776373-2facdaa6-472a-451c-8dc4-ddce910c3eb5.png)

**The new issue has a nearly-ready subject and it contains the checklist**
 
![Screen Shot 2022-09-12 at 4 40 36 PM](https://user-images.githubusercontent.com/11927811/189776657-d8014c19-5944-4121-bb0d-7441a6778464.png)

**Submit the issue and add to our Project.**

![Screen Shot 2022-09-12 at 4 43 53 PM](https://user-images.githubusercontent.com/11927811/189778151-34f410cf-131e-4556-b871-41e40fbdbd91.png)

![Screen Shot 2022-09-12 at 4 46 37 PM](https://user-images.githubusercontent.com/11927811/189778159-11eea069-66f0-4c58-a9be-1d70d8b5959d.png)

**Comment by stefaniebutland** [comment]
making good progress on this and issue templates seem like a good thing imo

**Comment by jules32** [comment]
Great! excited to see them briefly tomorrow during tech setup if there's time

**Comment by stefaniebutland** [comment]
Closing this issue. GitHub Issue Templates are in place and nicely functional. Modifying them as needed before I open an issue for the 2023-epa Cohort. 
- [Markdown source](https://github.com/Openscapes/cohort-planning/tree/main/.github/ISSUE_TEMPLATE) for templates
- [Choose an issue template](https://github.com/Openscapes/cohort-planning/issues/new/choose) to open an issue
