### ISSUE TITLE
add community call to events page

### ISSUE THREAD

**Issue by jules32** [Openscapes/how_we_work#194]

**Comment by jules32** [comment]
create events page with link to eventbrite registration, mark as "registration open"

**Comment by stefaniebutland** [comment]
comm call info: https://github.com/Openscapes/how_we_work/issues/190

**Comment by stefaniebutland** [comment]
Eventbrite questions for @jules32. We can discuss during some coworking if easier to screenshare and answer. 

**Tickets**:
- do you add text to appear after ticket purchase?
- What's your preferred  Default 'Reply-To' Email Address? hello@openscapes.org? (erin's gmail was there)
- do folks get reminder email(s)?

**Zoom**
- when & how do you add zoom link? Screenshot below  (step 3 Online Event Page) doesn't look like right place
- we should change to our Zoom, not Erin's. My permissions don't allow that.

![Screen Shot 2022-09-21 at 1 56 19 PM](https://user-images.githubusercontent.com/11927811/191608739-e12d7de3-646f-49d5-8448-16c81f5dd4b0.png)


![Screen Shot 2022-09-21 at 1 54 18 PM](https://user-images.githubusercontent.com/11927811/191608367-e3a4f845-4c19-43e2-b588-0f6b22e00a82.png)

**Comment by stefaniebutland** [comment]
[Draft pull request for Event Page](https://github.com/Openscapes/events/pull/15), ready to add registration link

**Comment by jules32** [comment]
Hi @stefaniebutland ,

I've added my Zoom link for the event (we'll revisit removing Erin's another day)

Your ticket questions: 

- do you add text to appear after ticket purchase?
  - we haven't done this in the past but please feel free to add
- What's your preferred Default 'Reply-To' Email Address? [hello@openscapes.org](mailto:hello@openscapes.org)? 
  - Yes let's do hello@
- do folks get reminder email(s)?
  - Could you send just 1 of the reminder emails? I believe there's a 2-days prior and 2-hour prior. Let's just do the 2-day unless you have a stronger preference

**Comment by stefaniebutland** [comment]
[published](https://openscapes.github.io/events/posts/2022-12-01-open-climate-movement-monica-granados/), tweeted & announced on Slack
