### ISSUE TITLE
sefsc blog post

### ISSUE THREAD

**Issue by jules32** [Openscapes/how_we_work#198]

**Comment by jules32** [comment]
Progress: Julie made a starting draft, Ady and Molly will add add content by Sept 27. Julie will review and add edits and @stefaniebutland  can post on Sept 29

**Comment by jules32** [comment]
Hi @stefaniebutland it's ready for you (Google Drive OpenscapesMain > CommsEngagement > Blogs) to prepare for posting!

**Comment by stefaniebutland** [comment]
@jules32 here's the [draft PR for you to check](https://github.com/Openscapes/website/pull/47). I still need to add alt txt to figs

**Comment by stefaniebutland** [comment]
published! https://www.openscapes.org/blog/2022/09/30/2022-sefsc-summer/
