### ISSUE TITLE
Move SEFSC-summer folder to completed

### ISSUE THREAD

**Issue by stefaniebutland** [Openscapes/how_we_work#199]
@jules32 Can I move [2022-noaa-sefsc-summer](https://drive.google.com/drive/folders/1TzOVeUSNzoS_fD1IBimm5gFtz2WP4etS?usp=sharing) Google Folder to completed?

**Comment by jules32** [comment]
yes please!

**Comment by stefaniebutland** [comment]
@jules32 🤔 What's the protocol for maintaining access for Champions to their Cohort Content when we move Folder to x_Complete?

![Screen Shot 2022-09-21 at 9 11 39 AM](https://user-images.githubusercontent.com/11927811/191558047-463ea721-1f4b-416e-87a7-88249687806c.png)


Questions that come up for me:  Will links to Google Folder break when I move it? Do I need to re-add all emails for access in new location? And tell folks it's moved?

**Comment by jules32** [comment]
Hi! Since we add all participants directly to this folder, their access won't change as we shuffle it into the x_Complete 😎

**Comment by stefaniebutland** [comment]
done :-)
