### ISSUE TITLE
Send digest issue to css, csu cohorts

### ISSUE THREAD

**Issue by jules32** [Openscapes/how_we_work#2]
Include: 

- [x] You've inspired us to get more organized with how to track things we come across. We created a public [Openscapes Zotero library](https://www.zotero.org/groups/4118402/openscapes/library) that we will continue to tag/organize. Also, we're using the [teaching-learning-resources repo's issues](https://github.com/Openscapes/teaching-learning-resources/issues) as a place to organize things we come across on Twitter. You are welcome to use and contribute to both of these!
- [x] Before next time, please check you have access to [our cohort folder](link to url). We know folks have multiple email addresses and we think we've captured them all there so you're ready for our next call but please let us know if we've missed something.

**Comment by erinmr** [comment]
Both docs are ready to go 

- [ ] [CSU COAST](https://docs.google.com/document/d/1uRPWatO1ElxTkSKXrUxLHX7U_22sXXKrtc8DdzhuJis/edit)
- [ ] [CSS](https://docs.google.com/document/d/1pXDxJD8ZrLNbmL-uglkY7Yk8qwhIy9fwHvQRuObsJeg/edit)

**Comment by jules32** [comment]
Sent 02 Cohort Call Digests with `Champions` label
