### ISSUE TITLE
Add Cohort Folder to Google Calendar invites

### ISSUE THREAD

**Issue by jules32** [Openscapes/how_we_work#202]
Suggested in SEFSC Coworking, folks go to Calendars to find the docs for those meetings. 

We can start by adding this to the Approach Guide (and GitHub Projects as we use them)

cc: @stefaniebutland

**Comment by stefaniebutland** [comment]
added in commit to Approach Guide
[Cohort tech setup under Google Workspace](https://openscapes.github.io/approach-guide/champions/pre-cohort-tech.html#google-workspace) description

**Comment by stefaniebutland** [comment]
need to add to GitHub Project checklist too

**Comment by stefaniebutland** [comment]
added to Participants Setup [issue template](https://github.com/Openscapes/cohort-planning/blob/main/.github/ISSUE_TEMPLATE/participants-setup---year-cohort-name---.md)
