### ISSUE TITLE
set up coworking on direct editing & reviewing on GitHub

### ISSUE THREAD

**Issue by stefaniebutland** [Openscapes/how_we_work#203]
requested by @mollystevens-noaa

**Comment by stefaniebutland** [comment]
I did a 7.5 min screenshare-and-tell video on this Jan 6. Too big to attach here 🤔

**Comment by jules32** [comment]
Could you upload it to our Slides folder, set permissions to view, and then link here?

**Comment by stefaniebutland** [comment]
Screenshare-and-tell of direct editing and reviewing a GitHub pull request ([Video](https://drive.google.com/file/d/1pN4WGhW5y6wro5B4MLp2PoehFZW03Rox/), 7.5 mins)
