### ISSUE TITLE
post SE-TIM blog

### ISSUE THREAD

**Issue by jules32** [Openscapes/how_we_work#205]
Hi @stefaniebutland, would you be able to post this [SE-TIM blog post](https://docs.google.com/document/d/1Bt8uEtTOQ1-g2jCjjEZi9Fa_rKcPPJyba8MJnzXQwoM/edit?usp=sharing) on Monday? 

There are a few comments, could you incorporate them, and add captions? I can add the recording video

**Comment by stefaniebutland** [comment]
Can do @jules32. Looks like I can get high quality screenshots from the linked slides

I can tag authors in tweet. NASA handle to tag? https://twitter.com/NASAEarthData?

**Comment by jules32** [comment]
Yes that sounds great Stef, thank you!  I am not super strict with naming conventions but follow what I've done recently by saving-as a recent post and following what feels right from there!
