### ISSUE TITLE
Add Jan-March events to openscapes.org/events

### ISSUE THREAD

**Issue by jules32** [Openscapes/how_we_work#206]
## Priority: first

- [x] Pathways to Open Science - do this after Wednesday when we talk to Ileana
- [x] HPC talk - https://www.exascaleproject.org/event/openscapes/
  - details: [Openscapes: supporting better science for future us](https://docs.google.com/presentation/d/1uKtVnZR8X94tADAWEE1THHKCbvfBbg2PBcH8asaoJQQ/edit?usp=sharing) - January 11, 2023 - Julie Lowndes. [Best Practices for HPC Software Developers Webinar Series](https://www.exascaleproject.org/event/openscapes/) hosted by The IDEAS Productivity project, in partnership with the Department of Energy Computing Facilities of the ALCF, OLCF, and NERSC, and the DOE Exascale Computing Project (ECP). This talk is part of Lowndes’ 2022 [NSF Better Scientific Software (BSSw) fellowship](https://bssw.io/pages/meet-our-fellows)
- [x] ESIP - our session https://2023januaryesipmeeting.sched.com/event/1EwXx/better-science-for-future-us-openscapes-stories-and-approaches-for-the-year-of-open-science
  - details listed on the sched page above
  - Also add: Join us here and at several other ESIP sessions too: 
    - Amy Steiker speaking in [Enabling Open Science with NASA's Earthdata in the Cloud](https://2023januaryesipmeeting.sched.com/event/1EwXE/enabling-open-science-with-nasas-earthdata-in-the-cloud)
    - Julie Lowndes speaking in [Earth and Space Science Knowledge Commons: From vision to implementation](https://2023januaryesipmeeting.sched.com/event/1EwXQ/earth-and-space-science-knowledge-commons-from-vision-to-implementation)
- [x] AGU - 1 event page saying "3 posters and plenary lightning talk at AGU 2022" 
  - details can point https://nasa-openscapes.github.io/about.html#slides; the most recent 4 entries are from AGU

## Priority: OK if after ESIP

- [x] WIDS - https://www.widsconference.org/widsstanfordspeakers.html
  - abstract listed here https://www.widsconference.org/juliastewartlowndes.html
- [x] EPA Cohort page - can do this Tuesday as we plan
    - get EPA logo (not permitted)
- [x] Community Call - kyber - tentative March 28, between 10-12 PT
- [x] Univ Toronto: Fenwick & Lowndes talk & lunch, March 24 #216

**Comment by stefaniebutland** [comment]
@jules32 Do you still want Cohorts added to Events? e.g. EPA?

**Comment by jules32** [comment]
Yes please! It's a good way to catalogue our activities

**Comment by jules32** [comment]
Hi Stef! Would you please be able to make the events pages for these upcoming events? The main purpose is to be able to have a high-level view of our events with links to take people to find more information (and register as appropriate). Thank you!

**Comment by stefaniebutland** [comment]
checking them off the list above as I complete draft of each, for my own satisfaction :-) 
Working in [draft PR](https://github.com/Openscapes/events/pull/17)

**Comment by jules32** [comment]
Happy to merge them as they're done too! I've helped prioritize/categorize them a bit too

**Comment by stefaniebutland** [comment]
Very helpful thank you. 

AGU is in [this PR](https://github.com/Openscapes/events/pull/17).   
For remaining Priority:first items, I'll submit a separate PR by Mon Jan 16.

**Comment by stefaniebutland** [comment]
ok to close @jules32 ?

**Comment by jules32** [comment]
Yes thanks!
