### ISSUE TITLE
NMFS Fall Cohort blog

### ISSUE THREAD

**Issue by jules32** [Openscapes/how_we_work#211]
@stefaniebutland could you please facilitate this: review any progress in Molly's google doc, contribute some text from Digest 5, and slack/email folks to hear their updates

**Comment by stefaniebutland** [comment]
reviewed doc & pinged in Slack Jan 6

**Comment by stefaniebutland** [comment]
draft expected Fri Jan 13, 2023

**Comment by stefaniebutland** [comment]
Timeline

- Thu, Jan 19 - all components in the doc; harmonize the text
  - Amanda away till 19th; confirmed she will contribute PIFSC section before publication
- Tue, Jan 24 - publish and tweet
- Thu, Jan 26 - ESIP conference Openscapes panel (incl Ady and Josh)

**Comment by jules32** [comment]
worked through Jan 17; will revisit Jan 20

**Comment by stefaniebutland** [comment]
Em adding AFSC text Fri Jan 19

**Comment by stefaniebutland** [comment]
Published and tweeted. 
https://www.openscapes.org/blog/2023/01/24/2022-noaa-nmfs-fall/
https://twitter.com/openscapes/status/1618004507920859137
authors tagged in reply: https://twitter.com/openscapes/status/1618005777767366664
