### ISSUE TITLE
Champions Cohort: 2023-nasa-champions. April 19-June 14

### ISSUE THREAD

**Issue by jules32** [Openscapes/how_we_work#220]
Management of this project is here: https://github.com/orgs/Openscapes/projects/7

**Comment by stefaniebutland** [comment]
Last Cohort Call completed June 14. Working through issues for wrap up https://github.com/Openscapes/cohort-planning/issues/166 and summary blog post https://github.com/Openscapes/cohort-planning/issues/169

**Comment by jules32** [comment]
Created Zenodo release for this cohort: https://doi.org/10.5281/zenodo.8066433

Followed https://openscapes.github.io/approach-guide/approach/documentation.html#make-our-documentation-citable

**Comment by erinmr** [comment]
DataCite does mint DOIs for events. Zenodo doesn't have an option to choose that. There is a new-ish group ConfIDent that is minting DOIs for events. https://www.confident-conference.org/index.php/Main_Page This looks good for now.
