### ISSUE TITLE
Blog post: ESIP panel. Post late Feb or early March

### ISSUE THREAD

**Issue by jules32** [Openscapes/how_we_work#221]
Timeline gives us time to rewatch the recording before the blog post

- [x] Post at openscapes.org
- [x] Share url with Megan Carter to post on our Sched page
- [ ] Also: post at ESIP FigShare

**Comment by jules32** [comment]
Julie to review Stef's draft by March 3

**Comment by stefaniebutland** [comment]
draft sent to panelists March 7

**Comment by stefaniebutland** [comment]
@jules32 re: post at ESIP FigShare, what would we post there and do we do that with a login? (have not posted to figshare before)

**Comment by jules32** [comment]
Thanks Stef! 

We don't have a FigShare; I am not opposed to creating one but since we already have a Zenodo, would you be able to post it there? Then would you send the blog and Zenodo link to Megan Carter and ask her to add it to the Sched page?

Thank you!

**Comment by stefaniebutland** [comment]
Blog post is up on [ESIP session page](https://2023januaryesipmeeting.sched.com/event/1EwXx). Requested this before Julie suggested getting DOI. I'll try to get DOI for this.

**Comment by stefaniebutland** [comment]
Citation with DOI:
Corey Clatterbuck, Ileana Fenwick, Josh London, Luis Lopez, Cassandra Nickles, Adyan Rios, Stefanie Butland, Julia Stewart Lowndes, & Erin Robinson. (2023). 3 Approaches for the Year of Open Science (v2023.03.0). Zenodo. https://doi.org/10.5281/zenodo.7851263

Asked for citation to be added to our ESIP session page

**Comment by stefaniebutland** [comment]
Phew! got login access to modify our ESIP Sched page and added citation


![Image](https://github.com/Openscapes/how_we_work/assets/11927811/29d37531-e157-4152-bef5-89eff1850690)
