### ISSUE TITLE
DOIs for Openscapes blogs?

### ISSUE THREAD

**Issue by eeholmes** [Openscapes/how_we_work#226]
I think we talked about this awhile ago as a way to make the blog pieces more "citeable". Here is how NASA TOPs is sharing their presentations on Zenodo via a "community". An Openscapes community could be created on Zenodo and then talks (slides) and blogs uploaded there. Then they are archived and get a DOI.
https://zenodo.org/communities/tops/?page=1&size=20

**Comment by stefaniebutland** [comment]
@eeholmes woohoo! I created https://zenodo.org/communities/openscapes/. Started [documenting](https://openscapes.github.io/approach-guide/approach/tooling.html#sec-zenodo). Now to associate existing Openscapes records with the Community, add some key blog posts, and document.

Tracking this work in Create and populate an Openscapes Zenodo Community #232. Can we close _this_ issue?
