### ISSUE TITLE
EPA post cohort presentation, May 9

### ISSUE THREAD

**Issue by jules32** [Openscapes/how_we_work#231]
Notes from Gayle today: EPA final presentation - open invite to whole center

Share Approaches, what teams have learned

- Gayle will create a shared document, lead this like a mini cohort call ; collaborative note taking. This is a key habit
- And have a few lightening talks from teams
- Roll call and light prompt: favorite office snack
- Maybe 3x short prompts What’s something that resonated that you’d like to know more of
- Goal: showcase what we did, stir up interest in the future

And we'll use this as a way to prep the Blog post too

**Comment by jules32** [comment]
Send slide deck to teams May 3 for them to add

**Comment by jules32** [comment]
- Roll Call/Agenda (5 min)
- Gayle + Jeff short welcome - this was the pilot (5 min)
- What happened (5 min)
- lightning talks (15)
- How we did it /wrap up

**Comment by stefaniebutland** [comment]
Jim Hagy will present

**Comment by stefaniebutland** [comment]
[draft agenda](https://usepa.sharepoint.com/:w:/r/sites/CEMMCODSPilot-Private-ContractItems/Shared%20Documents/Private-Contract%20Items/[Agenda_EPA_CEMM_webinar.docx](https://usepa.sharepoint.com/:w:/r/sites/CEMMCODSPilot-Private-ContractItems/Shared%20Documents/Private-Contract%20Items/Agenda_EPA_CEMM_webinar.docx?d=w6d8dcf096818425e91e3e4c08f9996bc&csf=1&web=1&e=BHJ42k)?d=w6d8dcf096818425e91e3e4c08f9996bc&csf=1&web=1&e=BHJ42k) in sharepoint

**Comment by stefaniebutland** [comment]
@jules32 I didn't re-email Jim Hagy about slides. Figured "we'd" do that when you share your draft slides.

**Comment by jules32** [comment]
prepped, added slides link to openscapes.org/media

**Comment by jules32** [comment]
It was so great! Jim and Amara were especially awesome
