### ISSUE TITLE
Create and populate an Openscapes Zenodo Community

### ISSUE THREAD

**Issue by stefaniebutland** [Openscapes/how_we_work#232]
We want to create a Zenodo Openscapes Community as a "semantically meaningful group" of research products in order to make them easily citable and more visible.

## Steps

- [x] Create Sandbox community version; document how-to
- [x] Create official Openscapes Zenodo Community
- [x] Document what types of research products we want to include
- [x] Write documentation for curators
- [x] Write documentation for people wanting to associate their research products with the Zenodo Openscapes Community

### Step 1 Create Sandbox community version; document how-to
- [x] Research how to create a Zenodo Community
- [x] Research existing Zenodo Communities we like
    - Transform to Open Science ([TOPS](https://zenodo.org/communities/tops/))
    - Center for Scientific Collaboration and Community Engagement ([CSCCE](https://zenodo.org/communities/cscce/))
- [x] Create draft Openscapes Zenodo Community in Zenodo Sandbox: https://sandbox.zenodo.org/communities/openscapes/
- [ ] ~Associate example records with Sandbox Openscapes Community~
  - don't think we can do this with Sandbox because it requires editing an existing record with a non-existent community: "To add one of your existing records to the community, edit the record, add this community under the "Communities" section, save, and finally publish."  
- [x] Document in Approach Guide

### Step 2 Create official Openscapes Zenodo Community
~- [ ] Research how to grant other users permission to curate~
- [x] create new email address for curator because email username of person creating the community shows as curator name; Stef, Julie, Erin with access permissions
    - TOPS uses nasatransformtoopen username, CSCCE uses CSCCEadmin
- [x] Julie review and edit Sandbox version
  - note TOPS & CSCCE have very different description lengths; choose something timeless for index page; there's a Read more ... page but maybe best just to point ppl to our site so we don't have another thing to keep up to date.
- [x] Create the Community
- [ ] Populate with existing Zenodo records
- [x] Clean up record titles & author lists, e.g. Pathways, Lesson Series should not have version numbers in Title
- [x] Decide how to add license metadata since ours are mixed cc-by & mit I think 
![Screenshot 2023-04-13 at 12 49 13 PM](https://user-images.githubusercontent.com/11927811/231867669-28ad845c-1e47-4bce-84c2-56be0a25098e.png)
- [x] Research and document scope of what to curate and how to label them, starting with existing products 
    - Lesson Series, Cloud Cookbook, Pathways, journal articles, presentations
- [ ] upload key posts and presentations (those that don't yet have a DOI)

### Step 3 Write documentation for curators and for people wanting to associate their research products with the Zenodo Openscapes Community

See user stories below and create task list after the previous steps are done.
- [x] Associate an existing Zenodo record with the Openscapes Community
- [x] Create a new Zenodo record and associate it with the Openscapes Community
- [ ] Download all Openscapes Community records

## User stories
Taking the opportunity to practice using Eli Holmes' agile / scrum management resources. Started by drafting user stories and defining the minimum viable products. These might not fit properly in scrum-style user stories but they helped visualize different types of documentation that might be needed. I wonder if TOPS has this that we could adapt.

### User story 1
Who: As Openscapes Director, Julie wants Openscapes outputs to be in a repository, to be citable with DOIs and to have these together in a “semantically meaningful group”
What: Julie wants a Zenodo Openscapes Community populated with our quarto books, and selected presentations blog posts
Why: So others can see Openscapes products and impact and know how to cite our research products
Definition of done: 

- Openscapes Zenodo Community exists
- Populated with Openscapes research products

### User story 2
Who: As an Openscapes collaborator, Justin Rice wants to cite key Openscapes products and know where to easily find them.
What: Justin wants a one-stop shop that houses key Openscapes research products that are citable.
Why: So he can easily find citations to use in presentations and reports, and easily find out which NASA staff were contributors so he can assess Openscapes value and impact and share that. 
Definition of done: 

- Openscapes Zenodo Community exists
- Populated with Openscapes research products
- Documentation on how to access list of all resources or filter resource e.g. 'NASA'

### User story 3
Who: As an Openscapes Champion or contributor, Catalina wants to know how to add her presentation to the Openscapes Zenodo Community
What: Justin wants a one-stop shop that houses key Openscapes research products that are citable.
Why: So she can get more visibility for her work and for her contributions to Openscapes and to open science in general
Definition of done: 

- Openscapes Zenodo Community exists
- Populated with Openscapes research products
- Documentation of how to add an existing DOI-record (by editing that record), upload a research product that doesn't yet have a DOI, what products can be included, how these records are curated and by whom
- Inform community members of this resource and our intentions (blog post)

**Comment by stefaniebutland** [comment]
Using curator at openscapes dot org alias to Stef's email. Created Zenodo acct w username `curator`

**Comment by stefaniebutland** [comment]
Notes from Zenodo video (need to know how to give others curator & admin privileges)
- 50 GB file upload limit
- select license for the thing you're uploading / getting DOI for
- managing Zenodo Communties ([35:30 in video](https://youtu.be/yj2r8RayIX8?t=2130))
- Invite Members as curators or admins

**Comment by jules32** [comment]
Awesome job Stef!! 🥳

**Comment by stefaniebutland** [comment]
Items we want to curate strategically and document, in order of priority:
Then: others on zenodo [already mentioning Openscapes](https://zenodo.org/search?page=1&size=20&q=openscapes)
- [ ] ESIP 2023
    -     - Description: NASA, NOAA, EPA
- [ ] ESIP 2022
    - Description: NASA, NOAA, EPA
- [ ] improve how-to instructions for item already in Zenodo, use screenshot showing Edit button
- [ ] Share how-to link a Amy and ask her to add white paper (https://zenodo.org/record/7667299) to Openscapes Community  -> highest priority for non-Stef person
- [ ] ESDSWG slides
- [ ] NOAA Fall summary
- [ ] NOAA AFSC ~January 2022
- [ ] WiDS
- [ ] Rstudio::conf slides (does Mine already have Zenodo record for these?) (Julie: I don’t know)
- [ ] useR!2019 keynote

**Comment by stefaniebutland** [comment]
document: 

This address will automatically ensure people who use it will have their record added to your community collection: https://zenodo.org/deposit/new?c=openscapes

**Comment by stefaniebutland** [comment]
@jules32 for AFSC post for Zenodo, which one of these were you thinking of?

1. about Fall 2022 Cohort https://www.openscapes.org/blog/2023/02/16/2022-noaa-afsc-fall/

2. about early 2022 Cohort https://www.openscapes.org/blog/2022/04/07/afsc-supportive-forum/

**Comment by jules32** [comment]
Let's do the Fall 2022 one since it's more recent and links to the earlier one

**Comment by stefaniebutland** [comment]
@jules32 when you have time, 

Please add your ORCID ID to the following records
- [ ] [Supercharging Research with Open Data Science and Teamwork](https://zenodo.org/record/3776843)
- [ ] [Audience building for open source projects](https://zenodo.org/record/4313522)

and add these to our Zenodo Openscapes Community
- [ ] [Audience building for open source projects](https://zenodo.org/record/4313522)
- [ ] [Building communities of practice around environmental open data science](https://zenodo.org/record/3497306)

**Comment by stefaniebutland** [comment]
Hi @tsnow03 !  I'm part of the Openscapes Core Team. We're populating our new [Zenodo Openscapes Community](https://zenodo.org/communities/openscapes/) with a few relevant records that are already in Zenodo. 

Would you mind adding your [CryoCloud JupyterBook](https://zenodo.org/record/7576602)? We'd love to help resources like this be more findable as we help researchers as NASA migrates data and workflows to the cloud.

Approach Guide: [How to add your existing Zenodo record to the Zenodo Openscapes Community](https://openscapes.github.io/approach-guide/approach/tooling.html#how-to-add-your-existing-zenodo-record-to-the-zenodo-openscapes-community)

cheers!

**Comment by stefaniebutland** [comment]
@jules32 To get your rstudio::conf and useR!2019 talks in Zenodo, I don't know how to get a pdf of slides. Please let me know how to create a pdf, send me one, or whether you'd rather we not upload these.
- https://github.com/mine-cetinkaya-rundel/hello-quarto
- https://github.com/jules32/useR-2019-keynote/

**Comment by stefaniebutland** [comment]
##  Majority of Zenodo work is done, as of May 23, 2023:

[Zenodo Openscapes Community](https://zenodo.org/communities/openscapes) exists! Waiting for several existing records to be associated with it (owners tagged in comments above). Upload of 2 more talks pending - need pdfs from html presentations.

[Approach Guide](https://openscapes.github.io/approach-guide/approach/tooling.html#zenodo) Zenodo documentation is done. Will benefit from a review and revision, but not urgent.

Cleaning up some titles, citation text, and keywords

**Comment by stefaniebutland** [comment]
Planning to review current docs Mon May 29 with fresh eyes. This will help with next iteration of blog post planned for May 31 publication

**Comment by stefaniebutland** [comment]
[pull request](https://github.com/Openscapes/approach-guide/pull/65) ready for @jules32 review in synch with blog post

**Comment by stefaniebutland** [comment]
Closing this issue! Wooohooo mission accomplished
