### ISSUE TITLE
Champions Mindset slides rework

### ISSUE THREAD

**Issue by jules32** [Openscapes/how_we_work#234]
Update Slide decks links: 

- [x] Champions Series
- [x] 2023-nasa-champions website

**Comment by jules32** [comment]
Following Call 1 with 2023-nasa-champions, need to rethink. Pushing/talking too much (too much process), need longer times for Champions to talk, introduce themselves, discuss. Will work on this as a block, will involve Kyber, Slides, and Series book. 

Some ideas:

- move all POP/process stuff to Series. In Welcome email, suggest they review it before Call 1. 
- Welcome - move this process to Series/slides - think for OSSIC/EPA (finally make as video?)
- Pathways/Closing - also too much process. Focus on Reflections guidance
- Look for redundancy & omit - mindset slides
- Team intros?
- Be fierce with timing

**Comment by jules32** [comment]
I've done a big revamp: 

- Series: https://github.com/Openscapes/series/pull/33, https://github.com/Openscapes/series/pull/34
  - Highlights:
  - rewrote index.qmd to be pre-reading for Champions before Call 1
  - reworked intro, brought POP to top
  - Made sections: Cohort Calls, Seaside Chats, How We Work
  - Moved a lot of process from Call 1 Agenda and Slides into index.qmd
- Kyber: https://github.com/Openscapes/kyber/pull/60, https://github.com/Openscapes/kyber/pull/61
  - Highlights: 
  - Shortened Welcome since less process
  - Lengthened Intros so teams can meet in small breakouts (depending on group might be best as teams around the room)
  - Refocused Closing – no POP, instead: Pathways Doc and there is time for questions
- Slides: [Mindset](https://docs.google.com/presentation/d/1fXgrWU5AMrZwgvpjs2J0dRT9x1Tc-IZyQIn8yPZSGM8/edit#slide=id.g20697681450_0_511) 
  - Highlights:
  - I removed Star Wars, first Mindset intro only 3 slides

TODO: 
- [ ] Update Approach Guide with Welcome email text for Fred Hutch, asking folks to read this first page of the Series. ("The Lesson Series will be a resource for you throughout the Cohort").

**Comment by jules32** [comment]
@stefaniebutland before Aug 23 (Hutch coworking) would you please read through the new Series homepage: https://openscapes.github.io/series/

All feedback welcome; and specifically please look for: 
- clarity and readability
- are there other things folks should know as process, either before Call 1 or to review during the Cohort?

Thank you!

**Comment by stefaniebutland** [comment]
Pull reqeust: https://github.com/Openscapes/series/pull/35

**Comment by jules32** [comment]
Woop woop, thanks Stef! Closing this huge issue, woot!
