### ISSUE TITLE
Make our Slack more open ... in steps

### ISSUE THREAD

**Issue by stefaniebutland** [Openscapes/how_we_work#236]
While Slack is Openscapes' [cozy web](https://maggieappleton.com/cozy-web), it's not open enough to people who really belong here. Pros and cons of gatekeeping in the cozy web - impt role for the team keeping psychological safety but (our) Slack is not accessible / open enough for the people who belong here to find us.

- [x] add to Approach Guide that we want our Slack workspace to be a supportive, trust-based community of folks doing data intensive science. Bound by our Code of Conduct. Current Slack members can invite others to join - an informal sponsorship approach
- [ ] Let NASA Mentors know they can request to invite folks as some have been doing. 
- [ ] When new folks join NASA Cookbook Hackday, ask if they want to join Slack
- [ ] Pathways "@channel Would you like to see more of your peers here ...."
- [x] Extend this to EPA Champions when they're invited after Cohort - as a way to bring other colleagues or other collaborating teams in; an extension of Seaside Chats
- [ ] capture record of the NASA channels (and any other relevant channels)
    - Archiving the channels themselves (reducing overlapping channels) is a good way to move to more open. Have design conversations and make decisions in GitHub Discussions and Issues.
- [x] Move Slack back to free version with only 90 days of history, ~May/June 2023

**Comment by stefaniebutland** [comment]
PR: update Slack info in Tooling and Cohort Tech Setup [#59](https://github.com/Openscapes/approach-guide/pull/59)

**Comment by stefaniebutland** [comment]
Erin opened up [GitHub Discussions for NASA Cloud Cookbook](https://github.com/NASA-Openscapes/earthdata-cloud-cookbook/discussions)

**Comment by stefaniebutland** [comment]
Where in GitHub Discussions would we "move" conversations like recent ones in #cloud-infrastructure? Or are they ideal for Slack? Trying to get a more general sense of which discussions / people would be impacted most by move back to free Slack with limited history kept

**Comment by stefaniebutland** [comment]
Plan to revert to free Slack Aug 2023. 

- [ ]  DATE Post #general @channel We will be moving to the free Slack plan on DATE. At that time, we will only have access to messages posted in the last 90 days. Why? We work in the open. Resources and answers that are valuable to one of us may be valuable to others. How? Post to Cookbook Discussions, other. On DATE we will post a reminder and export content and store it HERE so we can search for past shared resources
- [ ] DATE export Slack content; post its location to Slack #general

**Comment by stefaniebutland** [comment]
Set monthly reminder to #general 

 /remind #general Hi everyone! Don’t forget to add your affiliation in your slack profile. A picture would be great as well so people can recognize you. every month

about Slack reminders (should work on free plan) https://slack.com/help/articles/208423427-Set-a-reminder

**Comment by stefaniebutland** [comment]
Discussion w Julie Aug 8, let's socialize the transition but not yet set hard date to go to free Slack.

**Comment by jules32** [comment]
Socialize to answer questions: 

- When we share valuable resources, where we we share them so they're not locked in our Slack? 
  - Eg Where to put Matt Fisher's reading list for open source?
- And if you have colleagues that you'd like to join our Slack, we aren't limited

**Comment by stefaniebutland** [comment]
We've decided to keep Slack as is on paid plan for now. 
Continue socializing having key resources / discussions outside of Slack in public places like GitHub Discussions or Issues

**Comment by stefaniebutland** [comment]
@jules32 Can we close this issue?

**Comment by stefaniebutland** [comment]
This thread seems to fit perfectly in GitHub Discussions. I've opened that up in [Approach Guide repo GitHub Discussions](https://github.com/Openscapes/approach-guide/discussions/85#discussion-5603681) and will put key points in this Issue there.

**Comment by jules32** [comment]
yes, let's close!

**Comment by stefaniebutland** [comment]
Fri Nov 17 Julie and Stef change to free Slack. 
- [x] create channel #coiled-openscapes; invite 8 Coiled staff to join Openscapes Slack, cp Openscapes members from Coiled hosted channel to ours, invite James B to #cloud-infrastructure
- [ ] Stef export public channels content as outlined above, Thurs Nov 16 afternoon
- [ ] post to #general about free Slack, 90-day history and more open places we can discuss
