### ISSUE TITLE
Pathways report & blog post April 26

### ISSUE THREAD

**Issue by jules32** [Openscapes/how_we_work#237]

**Comment by stefaniebutland** [comment]
published https://www.openscapes.org/blog/2023/04/26/pathways-report/

**Comment by stefaniebutland** [comment]
tweeooted ✅

**Comment by stefaniebutland** [comment]
@jules32 Is this open till report submitted? If not, ok to close

**Comment by jules32** [comment]
Thanks Stef, yes I will close when we submit tomorrow. Thanks!

**Comment by jules32** [comment]
Report sent, thank you!
