### ISSUE TITLE
Newsletter w/ Reflections Launch May 2

### ISSUE THREAD

**Issue by jules32** [Openscapes/how_we_work#238]

**Comment by jules32** [comment]
Draft start is [here](https://docs.google.com/document/d/1LURdYSKdoFu4UeEy8cPiZ4xkUtyprkGQ8hQnJqW1RbY/edit?usp=sharing); @stefaniebutland would you be able to look before we meet Monday afternoon? Any comments/edits/notes welcome! I'm wondering if this is just a Reflections announcement or a fuller newsletter. Thank you!

**Comment by stefaniebutland** [comment]
edits & feedback done May 1

**Comment by jules32** [comment]
Newsletter sent by Julie! 
Blog to be posted by Stef May 2. Thank you!

**Comment by stefaniebutland** [comment]
published: https://www.openscapes.org/blog/2023/05/02/news-may-2023/ 

tweet/toot May 2

**Comment by stefaniebutland** [comment]
tweeted/tooted
@jules32 ok to close issue?
