### ISSUE TITLE
BSSw openscapes blog post - Aug 23

### ISSUE THREAD

**Issue by jules32** [Openscapes/how_we_work#239]
I've written my final fellowship report and it's ready to be posted as a blog post. Thinking this can wait until early June since we have several other posts for May

related to #207

**Comment by jules32** [comment]
Note: the blog post will just be the Final Report Summary, it will end before the Milestones sections.

Thumbnail can be the Champions Series image.

**Comment by jules32** [comment]
Hi @stefaniebutland, could you please post this on the blog at the end of August? This will be good timing for the Posit::conf talk in September. 

Here is the stub, with everything that you need: https://github.com/Openscapes/website/blob/main/content/blog/bssw-fellowship.md/

**Comment by stefaniebutland** [comment]
can do! @jules32 I've marked my calendar to publish Wed Aug 23; Aug 20 looks like a Wednesday

**Comment by jules32** [comment]
great, thank you!

**Comment by jules32** [comment]
Yay, done, thank you Stef!
