### ISSUE TITLE
Mentors Seaside Chats

### ISSUE THREAD

**Issue by stefaniebutland** [Openscapes/how_we_work#243]
Resume regular Mentors Seaside Chats

Final Coaching May 1. Email May 3 (I - Stef - dropped the ball on this). First meeting Mon May 15? 

- 1st is Open Mic
- folks bring what they want to throughout the summer and see what they want to do to pick up in Fall

Date of last meeting before summer?  Let’s not do summer events (socials) this year

**Comment by stefaniebutland** [comment]
@jules32 I dropped the ball on this. Please respond inline below.

Should I: 

- create calendar invite Mon May 15, 12-1:00pm PT (short notice but can see who comes)
- recurring every 2 weeks for a year, or none in summer; what is last date before summer; when to resume in Sept?
- invite non-NASA Mentors
- invite NASA Mentors
- email invited Mentors (as before, giving heads up)

**Comment by jules32** [comment]
No problem. 

Yes having a few on the calendar through June would be good. I can't make May 15 or 22, and 29 is a holiday. We'll need to re-focus with NASA mentors so let's email only non-NASA. I think starting the 22nd is best for my June schedule and that gives more breathing room (ie not next week). What do you think?

**Comment by stefaniebutland** [comment]
Are you suggesting starting May 22 and I would lead (ok w me)? So May 22, June 5, 19 then end for summer?

**Comment by jules32** [comment]
That sounds great to me! We can pick up in August (and revisit if Mondays are best)

**Comment by stefaniebutland** [comment]
done
