### ISSUE TITLE
Website: review new website

### ISSUE THREAD

**Issue by stefaniebutland** [Openscapes/how_we_work#244]
https://github.com/Openscapes/website-new

Clone and build; see if any structural feedback or things we should be thinking. Add feedback in issue

**Comment by stefaniebutland** [comment]
🤔 Next time would I create this issue in the website repo, and link it to MainPlanning project? Wanting to associate issues with deadlines via milestones

**Comment by jules32** [comment]
Flagging for us to revisit the idea of a "Seaside Chats" page and where it would go: https://github.com/Openscapes/website-new/issues/5#issuecomment-1541408063

**Comment by stefaniebutland** [comment]
Finished May 19 review of the awesome new site! https://github.com/Openscapes/website-new/issues/14

Maybe Seaside Chats info would go on a new APPROACH > How we work page that also includes the FredHutch forked content

**Comment by stefaniebutland** [comment]
Site launched. Keeping this open for next phase review
