### ISSUE TITLE
Zoom test playing music during meeting

### ISSUE THREAD

**Issue by stefaniebutland** [Openscapes/how_we_work#249]
a small but non-trivial thing cause we keep having issues with it. Stef will test by recording in zoom and document what works

**Comment by stefaniebutland** [comment]
will test this: [How to share audio with shared visuals](https://support.zoom.us/hc/en-us/articles/201362643-Sharing-computer-sound-in-a-screen-share) via Zoom docs

because I can share audio from my computer (screenshot & link below), but can't seem to share screen (rotating welcome slides) at same time; that turns off the audio.

How to play background music on Zoom—without sharing your screen via [Zapier post](https://zapier.com/blog/zoom-music/)

![Image](https://github.com/Openscapes/how_we_work/assets/11927811/03cd4d2a-b685-4935-b92f-8b2a3ddab728)

**Comment by stefaniebutland** [comment]
## Two scenarios for sharing audio in Zoom

This Zoom resource covers both scenarios: [Sharing computer sound in a screen share](https://support.zoom.us/hc/en-us/articles/201362643-Sharing-computer-sound-in-a-screen-share). Ya gotta practice both beforehand cause on the fly will not cut it (as evidenced by recording myself trying it). 

IMPT: volume of shared sound is controlled in the source application. If spotify music is too loud, control volume in spotify (not your computer)

1. During start of meeting, sharing welcome slides in a loop, with music from spotify playing so audience can hear, and people speaking does not disrupt music. See "**How to share audio with shared visuals**".


![Image](https://github.com/Openscapes/how_we_work/assets/11927811/176e40eb-a634-436e-8b5d-0e0151ad5c1d)


2. During interludes where people are silent journaling, to share audio only, not screen. See "**How to play audio or music without sharing your screen**".


![Image](https://github.com/Openscapes/how_we_work/assets/11927811/0934172c-f8ea-47de-913b-dad0b9e6d976)

**Comment by stefaniebutland** [comment]
Documented in [Approach Guide > Tooling](https://openscapes.github.io/approach-guide/approach/tooling.html#zoom) 
whew!

**Comment by jules32** [comment]
Amazing, thank you so much for this!
