### ISSUE TITLE
Cohort Digests #4

### ISSUE THREAD

**Issue by jules32** [Openscapes/how_we_work#25]
- send surveys
- ask for team address for sending stickers
- you can invite us to a Seaside Chat as follow up from the schedule switch

**Comment by jules32** [comment]
After sent, Julie follow up with:

- [ ]  TXG group asking for individual addresses for stickers since they're a distributed team
- [ ]  Kenai group

**Comment by jules32** [comment]
@erinmr Here are the surveys: 

- [CSU-COAST](https://docs.google.com/forms/d/e/1FAIpQLScPVCTahAsTfhJzq5JS7JuQdele6EOFixWyPd_lGJ0Zy8S6nw/viewform?usp=sf_link)
- [CSS1: Openscapes](https://docs.google.com/forms/d/e/1FAIpQLSfG4B7YX6KV3uuX38UoLzsD7UiTDrS5w5tr8y7nDwxeeoTVNg/viewform?usp=sf_link)
- [CSS2: CS&S](https://form.jotform.com/210336069119048)
  - our event is called "Openscapes: Empowering diverse open data science leaders"

**Comment by erinmr** [comment]
- [ ] [CSS Draft digest ](https://docs.google.com/document/d/1e940xdpdCO9ox9aNCvth-faSRAP1Lbbn6Npkdx8hmfs/edit) ready for @jules32 review and edits

**Comment by jules32** [comment]
Hi @erinmr looks great, I made a few edits but they are ready to go. Thank you!
