### ISSUE TITLE
Reflections Program: May 9-26

### ISSUE THREAD

**Issue by jules32** [Openscapes/how_we_work#251]
https://openscapes.github.io/booklet/

**Comment by stefaniebutland** [comment]
- [ ] Stef make README in google folder with chat txt for resources, add playlist link
- [x] upload week 2 video

**Comment by stefaniebutland** [comment]
README doc now in Reflections folder. @jules32 if you still have week 1 Huddle chat.txt, please add it and I can clean it. (don't think ppl shared many resources in week 1)

**Comment by stefaniebutland** [comment]
- [ ] invite all Reflections participants to Slack after week 3 Huddle

**Comment by jules32** [comment]
Thanks Stef! I added the resources shared from 01 Huddle

**Comment by jules32** [comment]
Thank you email and survey sent; next step is the blog post

**Comment by jules32** [comment]
Started the blog post here: https://docs.google.com/document/d/1W9TUH81BD1nAmRV4rRD2y0V83MvFq0aJ4hL57xEhHXE/edit#

**Comment by stefaniebutland** [comment]
Closing this issue. Blog post issue: https://github.com/Openscapes/how_we_work/issues/275
