### ISSUE TITLE
Editorial manuscript

### ISSUE THREAD

**Issue by jules32** [Openscapes/how_we_work#255]

**Comment by jules32** [comment]
Started submission process!

**Comment by jules32** [comment]
Submitted! 🥳

**Comment by jules32** [comment]
TODO: Resubmit & Preprint

**Comment by stefaniebutland** [comment]
submitted. email confirmation received to me at gmail

> Thank you for your Preprint submission titled Shifting institutional culture to develop climate solutions with Open Science. A Moderator will review it before making a decision. Moderation criteria are detailed in the EarthArXiv moderation policy, available at https://eartharxiv.github.io/moderation.html.

>Regards,

>EarthArXiv Team
>https://eartharxiv.org/

website says: 
> When all submission requirements are met, EarthArXiv is typically able to moderate manuscripts within one week of submission.


![Image](https://github.com/Openscapes/how_we_work/assets/11927811/46b468ae-06b4-4627-bbf7-7c70c19cbaf7)

**Comment by stefaniebutland** [comment]
preprint has been published on EarthArXiv.  DOI: https://doi.org/10.31223/X5VM24

**Comment by jules32** [comment]
Submitted PNAS

**Comment by stefaniebutland** [comment]
submitted Nov 23

**Comment by jules32** [comment]
Resubmitted with revisions

**Comment by stefaniebutland** [comment]
Accepted!!!! Amazing work by @jules32 and so many mentors!

**Comment by jules32** [comment]
Reviewed/Submitted proof today; most license agreements signed

**Comment by stefaniebutland** [comment]
Accepted 🥳 !!!

**Comment by jules32** [comment]
Confirmed that all license agreements are complete!

**Comment by jules32** [comment]
We'll do a short blog post when it comes out, highlighting: 

- main take-away: coworking time
- cross-mentors community co-authors

Quotes to share: 

> Integrating Open Science into our work has led to indispensable scientific benefits and positive culture shifts, including expediting data workflows, improving the quality of research outputs, elevating our colleagues, building collaboration, and ultimately addressing climate change impacts. 


>To address our climate emergency, “we must rapidly, radically reshape society”—Johnson & Wilkinson, All We Can Save. In science, reshaping requires formidable technical (cloud, coding, reproducibility) and cultural shifts (mindsets, hybrid collaboration, inclusion).

**Comment by jules32** [comment]
Published!!

@stefaniebutland could you please to the following and then close this issue 🥳 

- post the blog (text below) on openscapes.org and cross-post nasa-openscapes.github.io - please feel free to add anything else if you'd like. Authors can be Openscapes or you could include all coauthors
- add published link to https://openscapes.org/media#publications; this is currently the 2nd down with 2023; please update to 2024 and can include the (preprint link in parentheses)
- close this issue!


## Blog text
Blog title: Shifting institutional culture to develop climate solutions with Open Science

We are so happy to share that a paper co-authored by Openscapes mentors across organizations – including NASA Earthdata, NOAA Fisheries, EPA, California Waterboards, Pathways to Open Science, Fred Hutch – and was just published: [Shifting institutional culture to develop climate solutions with Open Science](https://onlinelibrary.wiley.com/doi/10.1002/ece3.11341). From co-author Anna Holder, Cal EPA: “It’s short read and quite uplifting and inspirational and provides some more insight and what we’re learning as we implement Openscapes across organizations.”

> Our best advice to start shifting culture is to have regularly scheduled learning meetings—with structure and intention to make them different from other work meetings. 

Please let us know what you think, and share with colleagues! 

Citation: {TODO paste citation here}

**Comment by stefaniebutland** [comment]
Done 🥳
