### ISSUE TITLE
Mastodon follow list & notes on social platforms

### ISSUE THREAD

**Issue by stefaniebutland** [Openscapes/how_we_work#258]
start with finding Openscapes Mentors - add their handles to our ParticipantsMain (like ORCID IDs) and follow them

**Comment by stefaniebutland** [comment]
## related notes on social platforms and management

Buffer tool can manage scheduling Mastodon toots and other platforms. Hootsuite does not do Mastodon.

From Yanina Bellini Saibene in CSCCE Slack:
> At rOpenSci we are no longer use Twitter (here is our statment: https://ropensci.org/blog/2023/06/14/ropensci-communication-channels-en/).
For mastodon we develop our own system to post between several people without sharing credential (but it is a bit techie solution, here more detail: https://ropensci.org/blog/2023/05/17/scheduling-mastodon/).
Now there is Buffer that can be an option similar to TweetDeck for Mastodon: https://buffer.com/resources/mastodon-scheduling/

Alycia Crall (Carpentries) and Yanina 
> planning to work on a Mastodon tip sheet specific for our communities (rOpenSci, The Carpentries) to help onboard them to the platform,

**Comment by stefaniebutland** [comment]
wow, Bluesky looks intuitive. Originally spun out by Twitter, Inc ([wikipedia](https://en.wikipedia.org/wiki/Bluesky_Social))

**Comment by stefaniebutland** [comment]
[Accessibility Advisories](https://www.accessible-social.com/advisories) a list of known technology issues on different social media platforms that impact accessibility. If you find a social media accessibility issue that should be added to this page, please [contact Accessible Social](https://www.accessible-social.com/contact) directly.

**Comment by stefaniebutland** [comment]
Mentors followed on Mastodon
- Ady Rios
- Jeff Hollister
- Erin Steiner
Followed other community folks like
- Mara Averick
- Steve Crawford
- Jenny Bryan
- Sophie Breitbart

**Comment by stefaniebutland** [comment]
rOpenSci blog post by Steffi LaZerte could be super useful for us: [Scheduling Mastodon Posts in R with rtoot and GitHub Actions](https://ropensci.org/blog/2023/05/17/scheduling-mastodon/)

**Comment by stefaniebutland** [comment]
Re: Fosstodon, From Alycia Crall in CSCCE Slack 🙁. Watching the thread

 Fosstodon has started to become blocked on other servers because of their inconsistent quality of moderation ([example](https://fosstodon.org/@kev/110932586933979256)) and they announced today that [they are switching to invite only](https://hub.fosstodon.org/were-invite-only).

**Comment by jules32** [comment]
Ugh, what a bummer. Yes I think waiting on doing any more Mastodon community investment is smart right now :(

**Comment by stefaniebutland** [comment]
This thread seems to fit perfectly in GitHub Discussions. I've opened that up in [Approach Guide repo GitHub Discussions](https://github.com/Openscapes/approach-guide/discussions/85#discussion-5603681) and will put key points in this Issue there.

**Comment by stefaniebutland** [comment]
Mastodon Quick Start Guide
by Yanina Bellini Saibene, Oscar Masinyana, Alycia Crall
https://zenodo.org/records/10019853

**Comment by stefaniebutland** [comment]
Closing issue. We added text to Approach Guide in https://github.com/Openscapes/approach-guide/pull/88
