### ISSUE TITLE
Certificate of Completion - Champions Program - Oct 10

### ISSUE THREAD

**Issue by jules32** [Openscapes/how_we_work#259]
We can do this using kyber, and create PDFs that we upload to the Cohort Folder (no need to email everyone separately).

**Comment by stefaniebutland** [comment]
We made notes on how to approach this in Stef + Julie coworking doc. Stef will aim to do this in August if not sooner

**Comment by stefaniebutland** [comment]
Notes from discussion w Julie Jun 22

- **Goal**: work in a kyber branch to mock it up. Give NASA Cohort something by end of August - pdfs in Cohort Folder
- How can we make this automated and easy? For Cohorts, Reflections, Pathways (later maybe add Reflections as a row in CohortRegistry. Hello from Openscapes. NAME completed the Champs program on this date. URL/DOI. Sincerely, Openscapes Team (more of a letter than a certificate
- Look at the kyber source sheet and structure it that way using the data that’s there
- kyber_function(registry, particpants_list) %>% 
- Stef mock up a letter, like Dear PARTICIPANT NAME, blah blah $start_date
- https://github.com/Openscapes/kyber/tree/main/inst/agendas 
- Vision: kyber output is 40 pdfs named Openscapes-certificate-butland.pdf. Upload these in bulk to the Cohort Google Folder

**Comment by stefaniebutland** [comment]
Last 2023-fred-hutch Cohort Call is Oct 24. Have it ready then

**Comment by jules32** [comment]
Thank you Stef! Just cc'ed you on a request from a NASA Champion as well :)

**Comment by stefaniebutland** [comment]
**Openscapes Champions Program**

Certificate of Completion: <name>
Dates: month dd - month dd, yyyy

This certifies completion of the Openscapes Champions Program, open data science mentorship program for science teams. It is a multi-month program that is designed to ignite incremental and sustainable change within research teams and beyond. It helps teams get their own work done, while building skills and community within the realities of scientists’ busy schedules, varying expertise and needs. Learn more at https://openscapes.org/initiatives.

**Comment by stefaniebutland** [comment]
Draft PR WIP: https://github.com/Openscapes/kyber/pull/71
My first parameterized report. No help needed rn. Need to review what we did then take next step of populating certificate from spreadsheet via variables.

**Comment by stefaniebutland** [comment]
Woohoo! Code in this commit [Openscapes/kyber@`516f33a` (#71)](https://github.com/Openscapes/kyber/pull/71/commits/516f33a1f8272813f27db7585f02ec1de3a3aa2f) creates an html certificate from values in Registry Google Sheet. Next, create multiple certificates, one per participant.

<img width="962" alt="Screenshot 2023-10-11 at 10 22 27 PM" src="https://github.com/Openscapes/how_we_work/assets/11927811/93e0b481-44ba-4c26-9fa6-fd39b70011ff">

**Comment by stefaniebutland** [comment]
@jules32 I'm ready to ask for your help. I can create one html certificate from OpenscapesChampionsCohortRegistry Sheet and now want to create all certificates for a Cohort. I have a data frame subset of OpenscapesParticipantsMainList with only rows from one Cohort. Wondering how I cycle through to render one certificate for each row/participant.

Commit: [Openscapes/kyber@`9fd0481` (#71)](https://github.com/Openscapes/kyber/pull/71/commits/9fd048155b97814bebba75f19270d4747026196a)

**Comment by jules32** [comment]
This is awesome @stefaniebutland ! Wooo! Excited to review together next week!

**Comment by stefaniebutland** [comment]
For Fred Hutch Cohort we have certificates with surname only. Done not perfect. 
Leaving open

**Comment by stefaniebutland** [comment]
coworking with Ileana week of Feb 12 on this

**Comment by stefaniebutland** [comment]
We made certificates for Pathways. Code in new repo (cause it doesn't use kyber): [Openscapes/certificates](https://github.com/Openscapes/certificates).

Will tag Andy to help with Champions certificates since we still don't get first and last names in the output

**Comment by stefaniebutland** [comment]
@ateucher I'd really appreciate your R help in tweaking our code to make Certificate of Completion for Champions Cohorts. Let's set up a coworking slot once you've settled in. Next use of Certificate will be May 2024

**Comment by stefaniebutland** [comment]
Next, get both 1st and last names in certificates, in time for 2024 NASA Champs. Their Call 5 is May 29.
