### ISSUE TITLE
Mentors Seaside Chats, cross-org Mentors connecting

### ISSUE THREAD

**Issue by stefaniebutland** [Openscapes/how_we_work#260]
create new doc for new season
send calendar invite for biweekly Mentors Seaside Chats Aug 14 to Dec
link invite to Google doc

**Comment by stefaniebutland** [comment]
We are running biweekly Mentors Seaside Chats starting Aug 14 with current focus on Fred Hutch Cohort that starts Aug 29. Here's the email that went to all Mentors, incl NASA, on Aug9

Hello fine Mentors!

We’re resuming biweekly Mentors Seaside Chats Monday, August 14th, 12:00 - 1:00 PT / 9:00 - 10:00 ET after a summer break.  Look for a Google Calendar invite. You're **all welcome** to join **according to your schedules and needs**, with **no obligation**. This includes Openscapes Mentors from a wiiiide range of government and academic groups - NOAA Fisheries, NASA, CalEPA, Fred Hutch Cancer Center, Openscapes Pathways to Open Science, and others.

Seaside Chats are for building shared skillsets and learning together. They're a place where you can get familiar with any of the tooling and practices that we use. And, you can teach the rest of us what you know so that we can all work better together!

We'll use our usual Google doc [_SeasideChats [ openscapes-mentors ]](https://docs.google.com/document/d/1oYMKBT9U27TSDqHPeSTt_cWvX87NjlzdhwCZ_ZyZ4bc/edit) for agendas and collaborative notes and we'll email a reminder the week before each Chat.

Our primary focus for August - September will be skill-sharing to support the 1st ever Champions Cohort for the Fred Hutch Cancer Center with Mentors Sean Kross and Monica Gerber from the [Fred Hutch Data Science Lab](https://hutchdatascience.org/) (Sean developed the [kyber](https://openscapes.org/blog/2023-04-06-kyber/) R package that helps us create Cohort repos and Agendas!). This complements the 2nd annual [California Water Boards Openscapes Champions Cohort](https://openscapes.github.io/2023-swrcb/) August - October led by Anna Holder, Devan Burke, and Tina Ures. What else do you need? Let's get it on an agenda.

Cheers,
Stef and Julie

**Comment by stefaniebutland** [comment]
We now have weekly calls with NASA Openscapes Mentors, alternating Mentor Calls and Coworking.

Starting Wed Aug 28 we'll have biweekly NMFS Openscapes Mentors Coworking Calls with short term goal of prepping for 3 Fall Cohorts that will takeover Mentor Call slots starting Oct 8, 2024

**Comment by jules32** [comment]
Thanks Stef! Let's chat about how/when to do the cross-agency mentor calls as well. Maybe reaching out to them specifically about the upcoming Community Call with Ileana and me, and potentially having one cross-agency call at the end of the year as well.

**Comment by stefaniebutland** [comment]
Wed Dec 18, 1-2:30 fits NMFS Mentor Call slot, 2 weeks after the final NMFS Openscapes Champions Cohort Call

**Comment by jules32** [comment]
Let's think about coaching with Tara as part of this cross-Mentor effort!

**Comment by stefaniebutland** [comment]
closing.
