### ISSUE TITLE
AGU Abstracts due Aug 2

### ISSUE THREAD

**Issue by jules32** [Openscapes/how_we_work#264]
Julie leads a submission based on ESDSWG slides, abstract drafted

**Comment by stefaniebutland** [comment]
Submitted.

updated posted to Slack

> Re: Revised agendas for AGU Sunday workshops are due Aug 16. Catalina has proposed a refined agenda for our NASA Openscapes ½ day workshop (draft agenda). There are also 2 LPDAAC and 1 NSIDC workshops at the same time - would be great to reuse the same intro and earthaccess lessons as appropriate so we can co-develop single lesson(s) and have dry runs. Please have a look at the draft agenda & make edits & reuse in LP and NSIDC. We can use Aug 9 Mentor call for coworking on this, as well as Slack!
