### ISSUE TITLE
Carpentries Instructor Training

### ISSUE THREAD

**Issue by stefaniebutland** [Openscapes/how_we_work#269]
Julie, Stef, Danny Kaufman, Aug 9-10

https://github.com/Openscapes/how_we_work/issues/192#issuecomment-1668499014

**Comment by stefaniebutland** [comment]
Julie & Stef did Welcome checkout Aug 15.
teaching demo and community checkout event left

**Comment by jules32** [comment]
Julie passed teaching demo today

**Comment by stefaniebutland** [comment]
no teaching demo slots open (that fit Stef's sched). Sept 10 new dates will open up

**Comment by stefaniebutland** [comment]
shared by @BriannaLind: graphic of snapshot analogy for git commits (my teaching demo is git lesson) https://gitlab.com/git-stories/commit-guide#commit-guide

**Comment by stefaniebutland** [comment]
Woohoo! I passed teaching demo today. All requirements completed

**Comment by stefaniebutland** [comment]
@jules32 Can we close this issue with a 🙌 ?

**Comment by jules32** [comment]
I still have my community session, scheduled currently for Sept 14!

**Comment by jules32** [comment]
Julie completed with the community session yesterday! https://openscapes.org/events/2023-10-05-carpentries-community/ Woo!
