### ISSUE TITLE
Onboarding NASA Mentors

### ISSUE THREAD

**Issue by jules32** [Openscapes/how_we_work#272]

**Comment by jules32** [comment]
Updated: 

- nasa-openscapes.github.io/mentors
- cookbook/contributing/onboarding
- approach-guide/mentor-framework/onboarding

**Comment by jules32** [comment]
1:1's completed, this morning with PO.DAAC

## Next steps: 

- [ ] Double-check calendar invites, update ParticipantsList
- [ ] Email all new mentors, ask for GitHub Username in Particpants list, send them https://nasa-openscapes.github.io/earthdata-cloud-cookbook/contributing/onboarding.html

**Comment by jules32** [comment]
Emailed everyone

**Comment by jules32** [comment]
## Next steps for Stef
@stefaniebutland 

From the Participants list: 

- [ ] sleuth remaining GitHub Usernames
- [ ] add to 2i2c JupyterHub
  - [ ] add to 2i2c Access Sheet (listed in Column M)
- [ ] add to GitHub Organization with kyber
- [ ] add bios to nasa-openscapes.org/mentors

Update documentation in Approach Guide: https://openscapes.github.io/approach-guide/mentors-framework/onboarding.html#post-11-followup-checklist

**Comment by stefaniebutland** [comment]
When the above checklist is done, tidy sheet `2i2c Access Sheet (listed in Column M)`

**Comment by stefaniebutland** [comment]
need GH uname for Geoffrey Stano. The reset are in sheet.

**Comment by stefaniebutland** [comment]
added members w kyber 😁 

![Screenshot 2023-09-13 at 7 10 46 AM](https://github.com/Openscapes/how_we_work/assets/11927811/362a52d6-0d6d-43f4-9364-a3acd8daf051)

**Comment by stefaniebutland** [comment]
@jules32 can you please clarify

Approach guide says "Add to 2i2c as an administrator <https://openscapes.2i2c.cloud/admin>". I have added ppl as members, not admin. Does the phrase mean go to admin to add a member?

**Comment by jules32** [comment]
Yes we add people as members; in order to do so you need to be an admin with that url.

**Comment by stefaniebutland** [comment]
Approach guide is updated. See [Files changed](https://github.com/Openscapes/approach-guide/pull/87/files)

**Comment by stefaniebutland** [comment]
all Mentors names now on https://nasa-openscapes.github.io/mentors and intro statement updated "nine total DAACs".

For those without a bio, shall I add their DAAC below their name heading @jules32 and add bios as I/we find them?

**Comment by jules32** [comment]
Awesome, thanks so much Stef!

Yes that would be great if you'll add the DAAC name below. Could you also make a new logo compilation with all DAAC logos for the top? You can do in one of the NASA slide decks and we can reuse :)

**Comment by jules32** [comment]
Thanks @stefaniebutland 

Logos small on one line will be useful for other things (so keep in the hidden slide and github repo), but maybe here could you make bigger on 2 lines?

**Comment by stefaniebutland** [comment]
done https://nasa-openscapes.github.io/mentors.html

**Comment by jules32** [comment]
Thank you! One more thing - with those 4 you listed, would you move them to "past participants" at the bottom of the page mentors website page please.

**Comment by stefaniebutland** [comment]
All new Mentors now added to "all the things". Snapshot `Users_Sep15_2023` taken of sheet.

4 moved to "past participants" at the bottom of the page mentors website page.

**Comment by jules32** [comment]
So awesome, thank you!

**Comment by stefaniebutland** [comment]
Stef soon checking in w new Mentors via Slack DM and scheduling to present at upcoming Mentors Calls. Notes in 2023 NASA Mentors coworking doc

**Comment by stefaniebutland** [comment]
Nearly all new Mentors are signed up to introduce themselves at Mentor Calls.

still TODO: clean up the 2i2c users Sheet

**Comment by jules32** [comment]
Let's take this off your plate now Stef. Erin is leading the 2i2c users sheet cleanup now as she digs into cost and governance more.

**Comment by jules32** [comment]
@jules32 will confirm Mentors have access listed on the Participants spreadsheet

**Comment by jules32** [comment]
Hi @erinmr and @stefaniebutland 👋 

I've updated onboarding documentation as I've added new Mentors from LAADS DAAC. You'll get a few emails from me and see some merged PRs; this is just to consolidate a bit here for our information: 

- ✅ Sent welcome email to LAADS mentors, text saved in Approach Guide [onboarding page](https://openscapes.github.io/approach-guide/mentors-framework/onboarding.html) ([PR](https://github.com/Openscapes/approach-guide/pull/91))
- ✅ Updated Cookbook [onboarding page](https://nasa-openscapes.github.io/earthdata-cloud-cookbook/contributing/onboarding.html) ([PR](https://github.com/NASA-Openscapes/earthdata-cloud-cookbook/pull/260))
- ✅ Cookbook [setup page](https://nasa-openscapes.github.io/earthdata-cloud-cookbook/contributing/setup.html) now links to [2i2cAccessPolicies](https://github.com/NASA-Openscapes/2i2cAccessPolicies)  [PR](https://github.com/NASA-Openscapes/earthdata-cloud-cookbook/pull/261))
