### ISSUE TITLE
Community Call with Carpentries: Oct 5

### ISSUE THREAD

**Issue by jules32** [Openscapes/how_we_work#274]

**Comment by jules32** [comment]
Alycia Crall is coordinating a Carpentries Community Session with Erin Robinson and I as guests, along with Elizabeth Joyner and others at NASA. 

We'll cross-post: add to our events page, share, and blog about it

**Comment by jules32** [comment]
[draft agenda](https://docs.google.com/document/d/1hqoGigUseSNf7WcRyu1RLuoI8MjuljgdVxwfHWUahCs/edit#heading=h.3iueayrlu0hr) with session title and description

> Feel free to forward that invitation to any colleagues interested in attending. Folks can sign up to attend [on the Etherpad](https://pad.carpentries.org/community-sessions-2023). Let me know if you have any questions. Thanks, Alycia

**Comment by jules32** [comment]
@stefaniebutland could you please create an events page with the above info? I've asked if there is a link on carpentries.org to link to as well; we can add it when it is available.

Thanks!

**Comment by stefaniebutland** [comment]
- [ ] posted event: https://openscapes.org/events/2023-10-05-carpentries-community/ 
- [ ] linked to Event page in Sep 20 NASA kickoff Agenda
- [ ] added to OpenscapesEvents calendar
- [ ] [Carpentries Calendar](https://carpentries.org/community/#community-events) has it

**Comment by jules32** [comment]
Completed, 50 attendees! Carpentries will write a blog, we can cross-post or link to this event page when we get it.
