### ISSUE TITLE
Blog post: Fall Newsletter: Jan 24!

### ISSUE THREAD

**Issue by jules32** [Openscapes/how_we_work#277]

**Comment by stefaniebutland** [comment]
We asynch talked about where to compile / share Openscapes stories. Newsletter as one option. Putting this here, just in case

Openscapes Story!
Kourtney Burger’s [Slack post](https://openscapes.slack.com/archives/CHZ2SMN7J/p1694105507047059). Continuing what she started in Fall 2022 NOAA Fisheries Champs Cohort “My team and I are in the process of transferring our analysis methods to a quarto website ([here](https://sael-swfsc.github.io/adrift-analysis-methods/)) “. 
Matt Fisher, new NASA Mentor chimes in with some experience from his QGreenland workshop. Kourtney’s Dec 2022 post [Sound Bytes: Championing Open Science](https://openscapes.org/blog/2022-12-09-case-study-swfsc-sael/index.html) (and on [NOAA Fisheries site](https://www.fisheries.noaa.gov/science-blog/sound-bytes-championing-open-science))
Julie: I love this. How can we capture/share moments like these (with consent or anonymously)? Can we include in Newsletter, or have a running Slide Deck? Stef could you find a place and we can compile?

**Comment by stefaniebutland** [comment]
- Champions Cohorts
  - Hutch
  - SWRCB 2nd annual fork and building to future
- EarthArXiv preprint Editorial - first time collaborative writing a paper this way - Julie tips, what worked well/ was challenging?
- new NASA Mentors - goals for year 3

**Comment by jules32** [comment]
Shout-out to PIFSC: 

> Open science is a fundamental cultural change in how we conduct science by moving towards practices and workflows that promote reproducibility, transparency, sharing and collaboration, and usability of scientific innovation. A shift toward open science can take place in big and small steps, and benefits our collaborators, stakeholders, and future selves. As the [NOAA Fisheries Open Science](https://nmfs-opensci.github.io) initiative becomes [fully enabled](https://www.youtube.com/watch?v=ZA6jwLyuIRU&t=2467s), you will learn more about ways you can engage. In the meantime, we have a growing PIFSC Open Science Community of Practice and we want to stay better connected!

**Comment by jules32** [comment]
We'll wait until we have dates for Pathways and any info needed to ask for the First Five Years

**Comment by stefaniebutland** [comment]
PR for newsletter https://github.com/Openscapes/website-new/pull/86
