### ISSUE TITLE
Coiled coordinating

### ISSUE THREAD

**Issue by jules32** [Openscapes/how_we_work#278]

**Comment by jules32** [comment]
Meeting with Coiled team Monday for checkin; Meeting with Amy Tuesday to draft blog

**Comment by stefaniebutland** [comment]
discussing a November community call

**Comment by jules32** [comment]
Plan this spring: 

- Aronne shares his story April 3 at NASA Champions Cohort - better science in less time. James drafts blog post and cross-post on openscapes blogs
- Dean shares his story in Feb at JPL; James drafts blog post and cross-post on openscapes blogs

**Comment by jules32** [comment]
Have moved the work along and closing
