### ISSUE TITLE
Blog post: upcoming at AGU - Oct 17, Nov 29

### ISSUE THREAD

**Issue by jules32** [Openscapes/how_we_work#279]
Hi @stefaniebutland let's have a blog post right before AGU where we list the NASA Mentors talks / posters / public activities for more visibility. 

When these are announced (mid Oct)? would you be able to compile and post? I can help write the intro / framing as we get closer. To include: 

- Matlab talk; Mathworks booth

This is a long-term TODO now, but to get it on the radar.  :)

**Comment by stefaniebutland** [comment]
Next step is after AGU schedule of talks / posters is announced.

**Comment by stefaniebutland** [comment]
Creating GitHub home for AGU planning in https://github.com/Openscapes/how_we_work/issues/281

**Comment by jules32** [comment]
Posted at https://openscapes.org/blog/2023-12-10-agu-fall-meeting/ and https://nasa-openscapes.github.io/news/2023-12-10-agu-fall-meeting/
