### ISSUE TITLE
Blog post: MATLAB in the Cookbook - Oct 17

### ISSUE THREAD

**Issue by jules32** [Openscapes/how_we_work#280]
Plan: 

Lisa Kempler from MathWorks will draft, Julie/Erin will edit/contribute; Stef will make final edits for clarity and post! 

Purpose: showcase MATLAB in the Cookbook and JupyterHub with the new tutorials and how to's and give a heads up about our (hopefully accepted) talks and the Mathworks booth at AGU

**Comment by jules32** [comment]
Plan to have final edits by Oct 16 and I'll share with you @stefaniebutland  to post on Oct 17

**Comment by jules32** [comment]
Hi Stef! Here is the blog text for Matlab! https://docs.google.com/document/d/11RfUx7wqRM9zGCxo1rO4GMbvEVvtOXJ-/edit

**Comment by stefaniebutland** [comment]
[draft PR](https://github.com/Openscapes/website-new/pull/65). Stef will review 2nd half, add alt txt, format footnote, then publish & tooooot
