### ISSUE TITLE
EPA RUG talk, Fenwick & Lowndes - Oct 17

### ISSUE THREAD

**Issue by jules32** [Openscapes/how_we_work#284]
## Background: 

https://github.com/USEPA/workshops/tree/main/r/2023/epa_r_workshop_2023

Invited by Jeff Hollister

Previous years: 

https://github.com/USEPA/workshops/tree/main/r/2021/epa_r_workshop_2021

https://github.com/USEPA/workshops/tree/main/r/2019/epa_r_workshop_2019

**Comment by jules32** [comment]
Hi @stefaniebutland could you please create a small events page for this event? We don't have a ton of details from the link but you can use that language you see and say it's part of a X-day R users event at USEPA :)

Thank you!

**Comment by stefaniebutland** [comment]
https://openscapes.org/events/2023-10-17-epa-rug/

**Comment by jules32** [comment]
Thanks Stef!
