### ISSUE TITLE
Water Boards Champions Cohort Blog post start Nov 13, pub Dec 13

### ISSUE THREAD

**Issue by jules32** [Openscapes/how_we_work#286]
hi @stefaniebutland as the Water Boards Cohort continues and wraps up, would you please work with Anna, Tina, Devan to post their summary? Excited to include Em and Corey as guest teachers and strenthening/extending partnerships as folks commit to real change like in that quote Anna shared (via email, hopefully to share with permission). Amazing.

**Comment by stefaniebutland** [comment]
Stef starting this with Anna in Nov 13 Waterboards Huddle

**Comment by stefaniebutland** [comment]
Anna, Devan, Tina, Stef co-wrote over 3 Seaside Chat sessions. Anna will ping Stef & Julie when final version is ready. Aim to publish week of Dec 11.

**Comment by stefaniebutland** [comment]
Anna, Tina, Devan completed post. Stef to review Mon Dec 11 and publish ~Dec 13

**Comment by stefaniebutland** [comment]
Published! https://openscapes.org/blog/2023-12-13-waterboards/
Tooted: https://fosstodon.org/@openscapes/111574550237621917 

Check out the [Water Boards blog category](https://openscapes.org/blog.html#category=water%20boards).
