### ISSUE TITLE
Amy Steiker et al NSIDC UWG Blog post - Oct 13 or 16

### ISSUE THREAD

**Issue by jules32** [Openscapes/how_we_work#287]
Julie to help shape 

[UWG slides](https://docs.google.com/presentation/d/1NEsE58SIMjQ_fjC_11HIXqd7Urvi5yy5/edit#slide=id.g23808f09f20_2_714) about Managed JupyterHub options, they are :sparkles: amazing :sparkles: and available for sharing/reuse with your DAACs and communities.

**Comment by jules32** [comment]
Hi @stefaniebutland , would you be able to post [this blog post](https://docs.google.com/document/d/1a_QcSBoVzxg3q0EtlN6qKoJ21xahOKUwxBM1hwsYXec/edit) on Friday or Monday (we'll have #280 on Tuesday)? 

As always, please review and add any update anything that would help clarify the text, check formatting, and add alt text. Thank you!

**Comment by stefaniebutland** [comment]
Can do Friday @jules32

**Comment by stefaniebutland** [comment]
PR ready to publish & toot Fri Oct 13 https://github.com/Openscapes/website-new/pull/64

**Comment by stefaniebutland** [comment]
@jules32 question about the "look"  
1. Including people's ORCID links (a good thing) looks like it forces each author to be on a separate line. Is this ok? or do you prefer all on one line, no ORCID links?
1. In this post are you ok with the title & subtitle? Titles look crowded when too long



![Image](https://github.com/Openscapes/how_we_work/assets/11927811/69441063-ae4b-4074-8e5a-f22ff23f483f)

**Comment by jules32** [comment]
Awesome @stefaniebutland , thank you!

1. good with the orcid links, nice to display when we have them
2. great with 2 lines for better reading.

**Comment by stefaniebutland** [comment]
[Published](https://openscapes.org/blog/2023-10-13-nasa-jupyterhub-coiled/), tooted and Slacked

**Comment by jules32** [comment]
Wonderful, thank you!
