### ISSUE TITLE
Create cohort registry

### ISSUE THREAD

**Issue by jules32** [Openscapes/how_we_work#30]
Discuss how this would be best: GSheet or GHub?

Items: 
- cohort identifier
- start date
- # sessions 
- # teams and participants
- links to agendas

**Comment by erinmr** [comment]
started airtable here -> https://airtable.com/tbl1Gc5jvLu1MC8Bu/viwGgdP1A3y0E3tC1?blocks=hide

**Comment by jules32** [comment]
this is looking so great

**Comment by erinmr** [comment]
@jules32 - I exported this table to CSV and added to the [champions folder](https://drive.google.com/drive/folders/1RtmGsqIPt1U4g4Jl0c7aCA3MBlslZDqQ). Let me know if there are missing fields/more needed or if we can close this issue

**Comment by jules32** [comment]
This looks great! Thanks – I'll close
