### ISSUE TITLE
Book Club 2024

### ISSUE THREAD

**Issue by jules32** [Openscapes/how_we_work#302]

**Comment by jules32** [comment]
Re-coding America - Jennifer Pahlka
Designing & Leading Life-Changing Workshops by Ken Nelson, David Ronka, Lesli Lang, Liz Korabek-Emerson, Jim White

**Comment by stefaniebutland** [comment]
#bookchat or #bookclub channel? 
or GitHub Discussion  (where? how we work?) for keeping books list

**Comment by stefaniebutland** [comment]
Current thinking: Model after [rOpenSci Community Call Ideas repo](https://github.com/ropensci-org/community-calls/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) with an issue template for one issue per suggested book, so at a glance in the Issues page we can see number of comments made on a book and we can make labels like `0/idea`, ....`1/something`, ....`2/scheduled`. With scheduled meaning we'll do a ~1hr discussion. 

- [ ] create repo w README
- [ ] create Issue template
- [ ] Set up Slack notifications to #bookclub channel (See #test-gh-notifications channel for setup thanks to @mfisher87)
- [ ] add seed ideas as issues from Julie's above
- [ ] announce in Slack #general 

Issue template should have
- issue title structure w title of book
- who suggests it
- (optional) why read / the pitch / relevance to Openscapes community interests
- (optional) are you willing to lead the discussion and / or arrange a time? (Y/N)



![Image](https://github.com/Openscapes/how_we_work/assets/11927811/b008b21e-847b-4327-b885-9ed63360f36b)

**Comment by mfisher87** [comment]
* _Engaging Emergence_ - Peggy Holman ?

**Comment by jules32** [comment]
Sounds good @stefaniebutland! If you'd like to continue on this and describe in Slack channel the plan that's great. Encourage thoughts in the GitHub Discussion (so folks not in Slack can participate). I can write some starting thoughts at coworking today

**Comment by stefaniebutland** [comment]
It's happening, WIP 
https://github.com/Openscapes/book-club

**Comment by stefaniebutland** [comment]
Dialing back the process aspect by taking the checklist bits out of the issue template. Right now we're not planning to "(over)organize" a book club; rather we're putting bits in place so it can happen if people are interested.

Issue template for future use:

```
---
name: Suggest a book
about: Suggest a book for Openscapes Book Club
title: "[book] book name"
labels: 0/suggestion
assignees: ''

---
## The book

Book title (linked to a source), author(s)

Name of person suggesting the book: 

**The pitch. Why read it? What is the book's relevance to the Openscapes community?** 

Add your opinions here.

## Logistics

- [ ] I'd love to lead a discussion of this book (via Zoom)
- [ ] I can arrange a time and share a calendar invite
- [ ] Can someone from the Openscapes Team please help me arrange a time and share a calendar invite?
```

**Comment by mfisher87** [comment]
Awesome! Love the use of labels :star_struck:

**Comment by stefaniebutland** [comment]
Time to schedule a January 1-hr discussion of Recoding America

**Comment by stefaniebutland** [comment]
Woohoo! First book club was a success. Notes at https://github.com/Openscapes/book-club/issues/2
Closing this issue we used for planning the book club and we'll proceed in the https://github.com/Openscapes/book-club/ repo when people want to hold another session
