### ISSUE TITLE
Blog: NMFS Openscapes Mentors - Jan 24, 2024

### ISSUE THREAD

**Issue by stefaniebutland** [Openscapes/how_we_work#303]
start drafting in Dec 20 coworking session w Mentors.

**Comment by jules32** [comment]
Great session today with Mentors; next steps are 

- [ ] trimming intro
- [ ] turning bullets to text (consider the flow, make it a sentence, pull out into quotes, and also cut stuff)
- [ ] read-through thinking audience: perhaps flip background vs "what we did this fall" in a few sections (for example "how we're doing it"
- [ ] Craig Maillard to make a graphic of challenges (amazing!)

@jules32 to continue synthesis, tag Eli Holmes when tighter
@stefaniebutland to revisit with Craig in the new year, ping Mentors if they want to contribute further, and post

**Comment by stefaniebutland** [comment]
Awesome Mentors did all the things! Published Jan 24
