### ISSUE TITLE
New coworking calendar

### ISSUE THREAD

**Issue by jules32** [Openscapes/how_we_work#308]
@stefaniebutland could you please make a new Coworking Google calendar? Details in our notes doc. 

First priority is to add `earthaccess hackdays` to meet that immediate need for Feb 6. 

Then, please add other NASA Mentors hackdays.

**Comment by stefaniebutland** [comment]
update: We renamed OpenscapesCoworking Google cal to NASA-Openscapes and we invite the nasa-openscapes-mentors google group as guests, plus additional non-mentor guests as needed.

While this is the "best" solution right now, it did flood nasa mentors' Outlook inboxes with ~100 emails, apparently one per date event, despite the events like Mentor Calls being recurring. 🐵
