### ISSUE TITLE
Blog & wrap-up: Champions Cohort: 2024-nasa - July

### ISSUE THREAD

**Issue by jules32** [Openscapes/how_we_work#309]
Dates: April 3, 17, May 1, 15, 29. 

Take-over of our regular mentor calls

NASA-Openscapes ([planning issue](https://github.com/orgs/NASA-Openscapes/projects/7/views/1?pane=issue&itemId=50179279), [calendaring sheet](https://docs.google.com/spreadsheets/d/1ywZN6iq6Nl1WuwOBEA1hpQUhXKiY10dgWsvjUSJiaig/edit#gid=0))

**Comment by stefaniebutland** [comment]
Stef create 2024 Cohort page like https://nasa-openscapes.github.io/2023-nasa-champions/

**Comment by jules32** [comment]
@stefaniebutland would you be able to create a post on openscapes.org/events for the NASA Champions Cohort? Can be simple like last year's: https://openscapes.org/events/2023-04-19-nasa-champions/

**Comment by stefaniebutland** [comment]
2024-nasa-champions [repo](https://github.com/NASA-Openscapes/2024-nasa-champions), [website](https://nasa-openscapes.github.io/2024-nasa-champions/) are live.

Event page ready to publish with [this PR](https://github.com/Openscapes/website-new/pull/91)

**Comment by jules32** [comment]
@stefaniebutland no action needed; as an FYI I created 02_CallAgenda for 2024 NASA Champions by hand so that Catalina and Luis could start working there

https://github.com/NASA-Openscapes/workshop-planning/issues/37#issuecomment-1997870710

**Comment by jules32** [comment]
Woo great Final Call yesterday. 

Julie will focus on digest and blog; @stefaniebutland I've tagged you in a few things to help on the tech/coordinating side. Hopefully you can do that at the same time as you do the same for EPA.

**Comment by jules32** [comment]
Wrap-up details here: https://github.com/orgs/NASA-Openscapes/projects/11/views/1

**Comment by jules32** [comment]
Hi @stefaniebutland , 

The NASA Champions blog language has been approved, I've just cc'd you on the email with the most recent version. It is ready for posting when you have a chance.

Thank you!

**Comment by stefaniebutland** [comment]
Post is published, and promoted on Mastodon:
- https://nasa-openscapes.github.io/news/2024-07-24-2024-nasa-champions-cohort/ 
- https://openscapes.org/blog/2024-07-24-2024-nasa-champions-cohort/
- https://fosstodon.org/@openscapes/112843414407396379 

closing as completed
