### ISSUE TITLE
Quarto Contributing Clinic

### ISSUE THREAD

**Issue by jules32** [Openscapes/how_we_work#312]
Quarto Contributing Clinic idea - 1.5 hour session, (structured after GitHub Clinic, with 2x short slide decks and activities)

[POP](https://suzannehawkes.com/2010/04/09/pop-everything/): 

- Purpose: teach NASA Openscapes Mentors a workflow with Quarto and branch/pull requests. For contributing to Cookbook but also anything. Invite other Openscapes Mentors as a way to re-connect and skillbuild. 
- Outcomes: Mentors build skills, more empowered/equipped for contributing. Also we have a new clinic we can reuse. 
- Process: teach in late June(?), start with NASA Mentors to find a date (stand-alone, not part of our normal meetings?). Stef to lead design & teaching? Create 2 short Google Slide decks, design the activities. 

  1. Targeted intro to Quarto
  2. GitHub Workflow: How to make a branch, (draft) pull request, communicate what you’re doing

**Comment by jules32** [comment]
walk through https://openscapes.github.io/quarto-website-tutorial/

**Comment by stefaniebutland** [comment]
## Apr 23 discussion

Designing: What would you screenshare with a colleague when you’re first showing someone? Start with the activity, build the intro after

- Ultimately standalone, but meet NASA Mentors needs first so it needs to be in the Hub. 
- Counterpoint - Download this one qmd file and take it wherever you work?
- Minimal - Create small repo with a qmd and a ipynb and a yml file
  - Understand how to contribute using quarto, not how to set it up
  - Clinic will start w clicking pencil to edit in GitHub. That results in a fork. 
  - Quarto - explore file that has text and code; make some edits
  - Commit and push
  - Back to browser to do a pull request

Next mtg Apr 30

**Comment by jules32** [comment]
Thanks Stef! Thinking about this more, it should be focused on branches, not forks. Some more thoughts:

- Intro on big-picture workflow diagram: this is main, branch to make your edits, edits + render using quarto, PR to merge your branch
- [In hub] 
  - clone repo, make a branch
  - edit & quarto [ breakouts? ]
  - commit
- In GitHub
  -  pull request
  - merge together

**Comment by stefaniebutland** [comment]
I'll go through the [Quarto workflows > From Jupyter](https://openscapes.github.io/quarto-website-tutorial/quarto-workflows/jupyter.html) to refresh my Hub feels. I'm getting a sense what a 1.5 hr session could have.

❓ Would each person have their own clone in the Hub, so they branch, edit, commit, PR, merge to their own clone? 

I've added notes to bottom of our Coworking doc under "Quarto Contributing Clinic Design Notes" so we can comment/collab there in this phase.

**Comment by stefaniebutland** [comment]
Today I followed the [Quarto Website Tutorial > Workflow from Jupyter](https://openscapes.github.io/quarto-website-tutorial/quarto-workflows/jupyter.html), made notes and comments in our coworking doc and got happily opinionated. In Apr 30 Huddle, see our doc: Next step in Clinic Design, TODO Apr 30

**Comment by stefaniebutland** [comment]
May 3rd. Awesome 30-min huddle. Next steps:

- Make new stripped down repo: Openscapes/quarto-clinic. Use https://github.com/openscapes/quarto-website-tutorial as a template, keep Welcome, Explore and Setup, Workflow from Jupyter
    - add `_demo.qmd` - what’s in it?
        - Fix typo
        - Image with alt text
        - Code chunks in python & R
    - (later) add an `ipynb` since we want ppl to be able to add their tutorials

- while drafting, where screenshots or files are needed, leave notes
- Consider: do we use google slides? Or teach from the book? TEACH FROM THE BOOK!!
- Pull requests - revisit later - we’re not going to merge any people’s edits, so what does this look like to be realistic and effective?

**Comment by stefaniebutland** [comment]
@jules32 will propose these dates to NASA Mentors on ~May 6

Option A: Thursday Jun 27, 2024 ⋅ 10am – 11:30am Pacific Time
Option B: Thursday Jun 27, 2024 ⋅ 12pm – 1:30pm Pacific Time

🤔 do we list these on OpenscapesEvents, or NASA-Openscapes calendar? Probs NASA-Openscapes, invite google group and add other individuals like Eli

**Comment by stefaniebutland** [comment]
Clinic Wednesday, June 26⋅12:00 – 1:30pm
Email & cal invite sent to 2024 NASA Mentors

June 11, Stef will get Julie & Andy's input on draft Part2 GitHub

**Comment by stefaniebutland** [comment]
Julie async review Wed Jun 19

**Comment by jules32** [comment]
Piloted this with 3 participants on June 26; 

From Stef: Here are the resources from Wednesday's Quarto + GitHub Clinic:
[Agenda/ notes doc](https://docs.google.com/document/d/1A3hW2leoreaabsmkgvR45UxlWwOE7KksdzfU2vkxb-s/edit)
[Recording](https://youtu.be/ih5BehXbZ1U) of full session (1.5hrs)
[GitHub repo](https://github.com/NASA-Openscapes/quarto-clinic)
[Quarto website](https://nasa-openscapes.github.io/quarto-clinic/) generated from repo; No slides! It's all in the site.
Thanks for the feedback from those who participated! We'll iterate and offer this again in future.

We debriefed quickly saying it worked well to show code & _quarto.yml in the discussion following the first Breakout. 

- [ ] Before we lead again we can also review https://www.youtube.com/watch?v=Lum7irkP6k8, linked from https://openscapes.github.io/series/core-lessons/github/index.html

**Comment by stefaniebutland** [comment]
closing as completed
