### ISSUE TITLE
Blog post: White House Factsheet!

### ISSUE THREAD

**Issue by jules32** [Openscapes/how_we_work#316]
Openscapes mentioned in the White House Factsheet!
https://www.whitehouse.gov/ostp/news-updates/2024/01/31/fact-sheet-biden-harris-administration-marks-the-anniversary-of-ostps-year-of-open-science/

highlight the core group of mentors to let them get a little bit of the reflected glow. Maybe a pic and a little blurb about what NMFS Openscapes has meant for them

And: add a link to this from the home page?

**Comment by jules32** [comment]
https://github.com/Openscapes/website-new/pull/93

**Comment by stefaniebutland** [comment]
published!
