### ISSUE TITLE
add MATLAB video to youtube

### ISSUE THREAD

**Issue by jules32** [Openscapes/how_we_work#317]
Stef could you please add Erin's MATLAB video to YouTube: https://drive.google.com/drive/folders/1en_SHtjtF4pUt4WU0SzyV16SEegjiwrT?usp=drive_link

Video description could be: 

This video shows how to launch MATLAB in 2i2c NASA Openscapes JupyterHub. It is created by Erin Robinson (Metadata Game Changers, NASA Openscapes), in collaboration and Cedric Wannaz and Lisa Kempler (Mathworks). Review the tutorial: https://nasa-openscapes.github.io/earthdata-cloud-cookbook/tutorials/matlab.html

- [x] add to youtube
- [x] add a link to youtube from the top of Cookbook page under "this tutorial was written..."
https://nasa-openscapes.github.io/earthdata-cloud-cookbook/tutorials/matlab.html

**Comment by stefaniebutland** [comment]
PR needs review to merge: https://github.com/NASA-Openscapes/earthdata-cloud-cookbook/pull/304

**Comment by stefaniebutland** [comment]
merged
