### ISSUE TITLE
Blog post - impact with Nancy Maron - Sept

### ISSUE THREAD

**Issue by jules32** [Openscapes/how_we_work#335]
Will share first rough draft with Nancy and First Five Years folks by April 30

**Comment by jules32** [comment]
Spent 40 mins this morning re-reading our meeting notes from Fall 2023 and pasting bullets/points into starting [blog draft structure](https://docs.google.com/document/d/1lTnBkpWE954HpZWwsZMKju8hZ0vLi76nSWawke9rVRo/edit). Have scheduled another hour of writing this week.

**Comment by jules32** [comment]
Wrote for 20 mins this morning, another scheduled this week

**Comment by jules32** [comment]
Shared with Nancy today, to revisit second half of May

**Comment by jules32** [comment]
Duplicate with #360

**Comment by stefaniebutland** [comment]
@jules32 apologies - I have not published this yet. Had thought I was waiting for your further review of the doc after headings were added by Erin

**Comment by jules32** [comment]
@stefaniebutland , let's hold on this for now; I am thinking how this goes along with the "first five years" post

**Comment by stefaniebutland** [comment]
ok, I'll re-close the issue
