### ISSUE TITLE
NOAA Enterprise Data Mgmt (EDMW) Talk - May 14

### ISSUE THREAD

**Issue by jules32** [Openscapes/how_we_work#340]
Julie to present about NASA Openscapes, hoping to co-present with a NASA Mentor. 

Planning Issue: 
https://github.com/NASA-Openscapes/workshop-planning/issues/61

**Comment by jules32** [comment]
@stefaniebutland would you please make a events page on openscapes.org and nasa-openscapes.github.io? Details in this issue: https://github.com/NASA-Openscapes/workshop-planning/issues/61

Details to include: 
- EDMW is an internal NOAA conf; add background sentence (in the first comment in the above issue)
-  NASA Openscapes was invited via Bri Lind; Julie Lowndes & Ian Carroll (OB.DAAC) will co-present
- abstract for our talk

Thank you!

**Comment by stefaniebutland** [comment]
done

**Comment by jules32** [comment]
Thank you!
