### ISSUE TITLE
Add Psych Safety recording to YouTube

### ISSUE THREAD

**Issue by jules32** [Openscapes/how_we_work#343]
Hi @stefaniebutland ! Could you please clip Matt Fisher's NASA Champions Call 3 recording and add to YouTube?
This was at his request; so permission already granted :)

**Comment by stefaniebutland** [comment]
On YouTube https://youtu.be/rzi-qkl8u5M and linked from [Lesson Series: Team culture](https://openscapes.github.io/series/core-lessons/team-culture.html)
