### ISSUE TITLE
Help request reconciling Quarto version I'm using

### ISSUE THREAD

**Issue by stefaniebutland** [Openscapes/how_we_work#345]
@ateucher another help request. I feel like this is up your alley 🙇🏼 . Not urgent; Quarto working fine for me AFAIK

I've got up to date R and RStudio but out of date Quarto? Is my Path pointing to an old Quarto version instead of inside RStudio? I think I had originally installed Quarto using homebrew.

[RStudio & Posit Workbench Release Notes](https://docs.posit.co/ide/news/) says in RStudio 2024.04.0 RStudio > About will "Show Quarto version information in the About dialog. (#14263)"

My RStudio is v2024.04.1 but RStudio > About does not show Quarto version
![Screenshot 2024-05-17 at 6 17 57 PM](https://github.com/Openscapes/how_we_work/assets/11927811/ae5ce653-a4f6-4f20-b02f-5d158df92e02)

My `quarto check` says
```
[✓] Checking Quarto installation......OK
      **Version: 1.3.450**
      Path: /Applications/quarto/bin
```

But [Quarto download page](https://quarto.org/docs/download/) says current version is 1.4.554

![Screenshot 2024-05-17 at 6 28 24 PM](https://github.com/Openscapes/how_we_work/assets/11927811/13ad591a-f512-4802-9ece-f85f5d3e73d3) 

```
stefaniebutland$ 

[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.1: OK
      Dart Sass version 1.55.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      **Version: 1.3.450**
      Path: /Applications/quarto/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.11.4
      Path: /opt/homebrew/opt/python@3.11/bin/python3.11
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with python3 -m pip install jupyter

[✓] Checking R installation...........OK
      Version: 4.4.0
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Library/Frameworks/R.framework/Versions/4.4-arm64/Resources/library
      knitr: 1.46
      rmarkdown: 2.26

[✓] Checking Knitr engine render......OK
```

**Comment by ateucher** [comment]
I don't believe quarto is bundled with RStudio, so the version of quarto you are seeing will be the one you installed yourself, via homebrew or from downloading from the website - it won't get upgraded when you upgrade RStudio.

I was able to see the quarto version via `Help > About RStudio` rather than `RStudio > About RStudio`. That is an unfortunate design quirk!

<img width="615" alt="image" src="https://github.com/Openscapes/how_we_work/assets/2816635/6222ff72-9868-41e2-bd06-7eeb07321232">

You can check if you previously installed quarto with homebrew by doing `brew list` - it should show up under the "casks" section. If it's there you should be able to upgrade it with `brew upgrade quarto` (if not, `brew install quarto`). Or you can do it by downloading from the downloads page. There's no real difference other than personal preference.

**Comment by stefaniebutland** [comment]
Resolved thank you!

`Help > About RStudio` distinction super helpful thanks!
I've downloaded new Quarto version and now I see it in `Help > About RStudio`

My thinking RStudio came with Quarto came from [posit community forum](https://forum.posit.co/t/how-to-update-quarto-version-installed-with-rstudio/167830/2)
> The quarto you are actually using is shipped with RStudio IDE. If none is found installed, it will be using that one. If you install a new one, RStudio IDE should find it, and use the new one.

Notes to self:
My Quarto had not been installed w homebrew, so likely was from Quarto site download
```
stefaniebutland$ brew upgrade quarto
Error: Cask 'quarto' is not installed.
```

**Comment by ateucher** [comment]
Oh that is good to know - I guess I was wrong!

**Comment by stefaniebutland** [comment]
was still a bit strange that it was using an older Quarto version despite me having up to date RStudio, but I'll let that one go ;-)

**Comment by ateucher** [comment]
Yeah, an interesting case. It [looks like RStudio ships with quarto v1.4.533](https://github.com/rstudio/rstudio/blob/main/dependencies/common/install-quarto#L25), but as it preferentially uses the one you have installed outside RStudio (as noted in the forum post), it used that one (an older version).
