### ISSUE TITLE
Posit::conf 2024 prep - Aug 13

### ISSUE THREAD

**Issue by stefaniebutland** [Openscapes/how_we_work#347]

**Comment by stefaniebutland** [comment]
Woohoo! talk done, felt great. Slides shared in a posit README of talks and in our OpenscapesSlides [ public ] folder along w my 1-min pitch recording. I'll open an issue for a blog post

**Comment by jules32** [comment]
Post README of slides: https://github.com/rstudio/rstudio-conf/tree/master/2024
