### ISSUE TITLE
EPA Lesson Series update & pdf - Aug 30

### ISSUE THREAD

**Issue by stefaniebutland** [Openscapes/how_we_work#348]
## Contract
> Within 30 days of the final research team meeting, provide a draft document that is an organized summary of freely available collaborative and open data science resources.

Draft due to Gayle Hagler July 7, 2024. Final version due 15 days after receiving her feedback.

## Discussion
A Quarto book – to be openscapes.cemm. .... site for EPA, and rendered into pdf. 
Idea is to be able to share with EPA folks who have not participated in a Champions Cohort. 

## Solution
[Openscapes Champions Lesson Series](https://openscapes.github.io/series/) provides exactly what is requested. Julie and Stef to each spend 2 hrs 
- update the site
- adding feature to output as pdf
  -  Stef started this in [Add pdf output option #44](https://github.com/Openscapes/series/issues/44)

**Comment by stefaniebutland** [comment]
Spent 2hrs on this. [Pull request ](https://github.com/Openscapes/series/pull/49)

**Comment by jules32** [comment]
Worked on this last week ([Pull request](https://github.com/Openscapes/series/pull/53)) and Andy has made it a PDF ([issue](https://github.com/Openscapes/series/issues/44)). I've sent it to the EPA team today.

**Comment by jules32** [comment]
I've also sent Word document for their review. We'll expect their edits on Aug 9th (or after Posit Conf)

**Comment by jules32** [comment]
Completed, via 2 big PRs to the Series.  cc @stefaniebutland 

https://github.com/Openscapes/series/pull/57
https://github.com/Openscapes/series/pull/58

Biggest changes were:
- shortening Welcome chapter (homepage) by creating a stand-alone "What to Expect" chapter
- creating a "Program Summary" page that has migrated info from openscapes.org/champions. 
- incorporating openscapes.org/faq into the "What to Expect" team page (https://github.com/Openscapes/website-new/pull/148)
