### ISSUE TITLE
ESIP session blog post - Aug 30

### ISSUE THREAD

**Issue by jules32** [Openscapes/how_we_work#353]
Details here: https://github.com/NASA-Openscapes/how_we_work/issues/61.

**Comment by jules32** [comment]
Julie to draft more and combine with Alexis' review of the breakout rooms. Will share with coauthors for approval, then post

**Comment by stefaniebutland** [comment]
Draft PR with post for Julie to review & publish: https://github.com/Openscapes/website-new/pull/145

**Comment by jules32** [comment]
Thanks Stef! 

Would you reply to the email thread that we'll plan to post Thursday or Friday and see if anyone has any further edits? 
Thanks!

**Comment by stefaniebutland** [comment]
published https://openscapes.org/blog/2024-08-30-esip-summer-2024/ & copied to NASA Openscapes
tooted, skeeted
