### ISSUE TITLE
Guest teach Better Science @Water Boards - Aug 7

### ISSUE THREAD

**Issue by jules32** [Openscapes/how_we_work#355]
Hi Stef, 

How about we plan to work on updating slides together and you'll lead?

**Comment by stefaniebutland** [comment]
Done! (it will be much easier next time I do this) 
Learned some things from how Anna facilitates and added notes to our coworking doc and to [NMFS Cohort Call 1 prep issue](https://github.com/orgs/nmfs-openscapes/projects/33?query=sort%3Aupdated-desc+is%3Aopen&pane=issue&itemId=73099084)
