### ISSUE TITLE
Summer/fall website events pages

### ISSUE THREAD

**Issue by jules32** [Openscapes/how_we_work#358]
Hi @stefaniebutland ! Could you please make events pages on Openscapes.org & nasa.openscapes: 
Thank you in advance!

## ESIP session 

- [x] Details & abstract: 

https://2024julyesipmeeting.sched.com/event/1eVNz/mt-pisgah-supporting-nasa-earthdata-users-in-the-cloud-nasa-openscapes-onboarding-and-fledging. 

Please list Mentors co-leading 

## Open Science "Dynamic Convergence" Workshop

Julie invited panel speaker

- [x] Details & invite to register: 

taking place on 18th and 19th September 2024 at the Darcy Hotel in Washington, DC. The event is hosted by the Open Research Community Accelerator (ORCA), in collaboration with CERN and UNESCO, with the participation of NASA and the National Science Foundation (NSF). - 

The workshop will bring together researchers, students, policymakers, funders, and other stakeholders to highlight impactful open science activities, explore collaboration opportunities, and find practical ways to speed up the global adoption of open science. More information about the program and logistics will be shared shortly.
We aim to bring together an inclusive mix of participants spanning geographies, career stages, and disciplines. Thanks to generous support from the Gordon and Betty Moore Foundation and the Templeton World Charity Foundation, we are able to subsidize some travel costs to eligible applicants.
Please use this form to express your interest in participating in the workshop: https://forms.gle/rm9aaahGXZNmj4bs9
Applications will close July 31, and successful applicants will be notified by August 6. We will be getting in touch soon with further information; don’t hesitate to contact me directly in case you have any questions.

## NIH 

- [x] Details: 

This event will follow up and share from this event: https://openscapes.org/events/2024-06-04-nlm-equitable-open-science/. Lead Maryam Zaringhalam recently gave a keynote summarizing at CZI Open Science Meeting: https://zenodo.org/records/12523362

Light event details: https://github.com/Openscapes/how_we_work/issues/354. 

- [x] Please also add https://zenodo.org/records/12523362 as a quick link in the italics section up top: https://openscapes.org/events/2024-06-04-nlm-equitable-open-science/

## California Water Data Consortium

https://cawaterdata.org/events/california-water-data-consortium-march-2024-data-for-lunch/ - includes YouTube video

- [x] Update event page https://openscapes.org/events/2024-03-19-ca-water-data-lunch/ with link above & YouTube link
- [x] Update media page with `(recording)` linked to YouTube

**Comment by stefaniebutland** [comment]
pull request: https://github.com/Openscapes/website-new/pull/123

**Comment by jules32** [comment]
Thanks Stef, I'll review the PR this afternoon. 

One additional event to add please:

- [x] Stef kyber talk at posit conf :)
