### ISSUE TITLE
Blog post - 2024 update - July 17/18

### ISSUE THREAD

**Issue by jules32** [Openscapes/how_we_work#359]
Hi @stefaniebutland ! I have a draft blog post in our Google Folder "Blog_OpenscapesStatusUpdate_2024summer"

Would you please: 
- [x] read through by our meeting on Tuesday. See what you think, is anything missing, would you add more, do you have questions? I'm looking forward to discussing together too.
- [x] Add links and any remaining TODO's 
- [x] Post on website July 17 or 18!

**Comment by stefaniebutland** [comment]
This is fantastic. I particularly love the personal tone. Growth, maturity, and sustainability of Openscapes comes across really well. I've left some things in 'suggesting' mode. Happy to follow up after we discuss.

**Comment by jules32** [comment]
Thanks Stef! I've accepted/addressed your suggestions, they were great. Looking forward to chatting about it and having it live! Thanks

**Comment by stefaniebutland** [comment]
published https://openscapes.org/blog/2024-07-18-openscapes-update/
