### ISSUE TITLE
Aronne Blog post - July 19

### ISSUE THREAD

**Issue by jules32** [Openscapes/how_we_work#361]
Julie will re-watch Aronne's Champions Better Science talk and make a short post to publish before ESIP talk on July 23. 

Plan:
- [x] write post by July 18 - @jules32 
- [x] post on websites on July 19 - @stefaniebutland 
- [x] Julie share with Aronne and Coiled on July 19

**Comment by jules32** [comment]
I've drafted this post in the NASA Openscapes site. I'll wait for feedback from Alexis before finalizing the PR on Thursday. https://github.com/NASA-Openscapes/NASA-Openscapes.github.io/pull/66

**Comment by jules32** [comment]
Hi @stefaniebutland , this is ready to go whenever you are :)

**Comment by stefaniebutland** [comment]
published
https://nasa-openscapes.github.io/news/2024-07-22-aronne-merrelli-fledging-parallelized-science-in-the-cloud/
https://openscapes.org/blog/2024-07-22-aronne-merrelli-fledging-parallelized-science-in-the-cloud/
