### ISSUE TITLE
Blog post - Pathways to Open Science report - Aug 6

### ISSUE THREAD

**Issue by jules32** [Openscapes/how_we_work#362]
Ileana will finalize the report on July 31 and we can confirm Aug 6 as a good blog post date

**Comment by jules32** [comment]
Also, we will cross-post this blog on the Pathways to Open Science site. 

This will involve creating the Blog and copying the past blog post with the `pathways` category, as we've done with NASA and NOAA

**Comment by jules32** [comment]
Hi @stefaniebutland , this is all set to be published as soon as you have time, doesn't need to wait until Aug 6. Please ping Ileana when it's published and she will share with coauthors.
Thank you!

**Comment by stefaniebutland** [comment]
Will be published & tooted/skeeted Mon Aug 5. I'll email Pathways team when done.

[post Preview](https://deploy-preview-133--dreamy-solstice-e71879.netlify.app/blog/2024-08-05-pathways-report/) on Openscapes blog | [Pull request](https://github.com/Openscapes/website-new/pull/133) is ready to be merged Monday, then copied to Pathways site blog

[Pathways site](https://openscapes.github.io/pathways-to-open-science/) has a blog page now!

**Comment by stefaniebutland** [comment]
Closed as completed

The 2024 Pathways Report post is published and promoted on Mastodon & Bluesky (authors listed in reply to original post there).

https://openscapes.github.io/pathways-to-open-science/blog/2024-08-05-pathways-report/
https://openscapes.org/blog/2024-08-05-pathways-report/

https://fosstodon.org/@openscapes/112911222810450280
https://bsky.app/profile/openscapes.bsky.social/post/3kyyozpnzi52o

**Comment by jules32** [comment]
@stefaniebutland Would you please add a "this is crossposted on the PREreview blog https://content.prereview.org/community-building-for-a-better-tomorrow/" to both openscapes.org and pathways blog - thank you

**Comment by stefaniebutland** [comment]
closed as completed
