### ISSUE TITLE
BlogNewsletter_2024 - Sept 16

### ISSUE THREAD

**Issue by stefaniebutland** [Openscapes/how_we_work#363]
Started in Google doc BlogNewsletter_2024_August

@jules32 If you move things into groupings you like and make some edits, I'll do another round of edits.
Please set a publication date. I'm happy to make sure that gets done

**Comment by jules32** [comment]
@stefaniebutland , this is such a great outline and start, thank you! I think late August is a great timeline for this, after Posit, before "Dynamic Convergence". How about Aug 27 - I'll update the title here

How about: 

- [ ] draft by Aug 26 @jules32 
- [ ] review by Aug 28 @stefaniebutland 
- [ ] any refinements @jules32 
- [ ] publish Sept 2 @stefaniebutland

**Comment by jules32** [comment]
@stefaniebutland , let's shift to Sept 3 publish date. I updated the timeline above :)

**Comment by jules32** [comment]
To add, update the links

- [ ] Exciting to see [Easier Access to NASA Earth Science Data in the Cloud](https://www.earthdata.nasa.gov/news/easier-earthdata-cloud-access-earthdatalogin) in NASA News! This focuses on 
[@Carl Boettiger](https://openscapes.slack.com/team/U05PW1P08GG)
’s work on the earthdatalogin R package, which complements the earthaccess python library. A very cool collaboration across NASA TOPS, NASA Openscapes, NOAA Fisheries Openscapes, and 2i2c - with collaborators 
[@Luis López](https://openscapes.slack.com/team/U0231CYHMNH)
 
[@yuvipanda](https://openscapes.slack.com/team/U049SP2TRDX)
 
[@Bri Lind](https://openscapes.slack.com/team/U03N2TBGSGZ)
 
[@Eli Holmes](https://openscapes.slack.com/team/U01UH0B65K4)
! (H/T [Carl on Bluesky](https://bsky.app/profile/cboettig.bsky.social/post/3kuo25s2zpv2a))

**Comment by jules32** [comment]
Hi @stefaniebutland let's plan to publish this on Sept 16. I'll have a draft by Sept 12 to share with you.

**Comment by jules32** [comment]
Hi @stefaniebutland , the draft is all set for you. 

As we discussed, please edit/tighten/add links as you see appropriate, and then post when ready. I noted where the email could end and additional info could be included on the blog page, but please use discretion to cut/say less since we can't cover everything.

This will be only blog post this week, so it can go out on Monday or Tuesday, whenever you complete it. 

Thank you!

**Comment by stefaniebutland** [comment]
got it!!

**Comment by stefaniebutland** [comment]
- [x] https://openscapes.org/blog/2024-09-17-news-sep-2024/
- [x] emailed to 870 subscribers: openscapes-news@openscapes.org
- [x] posted to Slack
- [x] cross-post & add preface
- [x] mastodon
- [x] bluesky

**Comment by stefaniebutland** [comment]
woops, forgot I need to use full URL, not relative paths e.g. `../../media.qmd` because I'm copying from Openscapes site to NASA, NMFS, Pathways sites. Going back to fix these

**Comment by stefaniebutland** [comment]
I missed this for Sept News

> Exciting to see [Easier Access to NASA Earth Science Data in the Cloud](https://www.earthdata.nasa.gov/news/easier-earthdata-cloud-access-earthdatalogin) in NASA News! This focuses on
[@Carl Boettiger](https://openscapes.slack.com/team/U05PW1P08GG)
’s work on the earthdatalogin R package, which complements the earthaccess python library. A very cool collaboration across NASA TOPS, NASA Openscapes, NOAA Fisheries Openscapes, and 2i2c - with collaborators
[@Luis López](https://openscapes.slack.com/team/U0231CYHMNH)

**Comment by stefaniebutland** [comment]
closed as completed
