### ISSUE TITLE
DWR Open Forum talk - Aug 22

### ISSUE THREAD

**Issue by jules32** [Openscapes/how_we_work#366]
Thank you for bringing together the Openscapes team and agreeing to present at the **Department of Water Resources (DWR) Environmental Coordination Committee (ECC) August Open Forum!** It will be held on August 22 from 10:00am-12:00pm and will include presentations in the table below. Please populate the table and plan your presentation to leave 5-10 minutes for questions.

If possible, below is a list of dates for items to keep us on track. Let me know if you need to move any of these deadlines!

August 9 – Short Presentation Abstracts and Speaker Bios

August 21 – PowerPoints and Handouts

August 22 – Open Forum

Feel free to schedule a short time to meet with us before the Forum or arrive at the Open Forum 15 minutes early to work out any presentation recording problems and test out your slides.

**Comment by jules32** [comment]
DWR is a single department. They do water conveyance and snow pack. One thing: they are in charge of levees (along with the army core). This group more engineers, R & Python users. DWConsortium - that audience was people interested in water data across orgs. Varies in terms of expertise

**Comment by stefaniebutland** [comment]
What could Openscapes look like within DWR?

**Comment by stefaniebutland** [comment]
Notes on where I'd fit 
- How we work, coworking to share practices, coworking w Anna contributing to kyber pkg 
- tech audience - we use Kyber R pkg for xyz (posit::conf talk slide)

Decided kyber is not what the audience needs at this stage. "Everybody loves a good HVAC system but they don't need to know how it works."

**Comment by jules32** [comment]
Abstract: Openscapes is an open source approach and community that helps researchers and those supporting research find each other and feel empowered to conduct data-intensive science. Openscapes was created in 2018 to solve common open data science problems, and because of immediate and long term impacts, the program and community continues to iterate, grow and evolve. We support open science as “kinder science for future us”: the vision is a scientific culture that is more efficient, more kind, and more collaborative, and that can uncover solutions faster together to the most pressing climate and social challenges. Our main activity is mentorship to build open source technical and collaborative leadership skills within and across teams and organizations, connecting groups and role-modeling open practices that are critical elements to helping shift towards open science. We often hear the question: “what does Open Science look like”? We’ll share examples and stories from the growing Openscapes community including NASA, NOAA, EPA, and the California Water Boards that supports open science as a daily practice, and actionable ideas teams can take to join the open science movement.

Bios
 Julia Stewart Lowndes, PhD
 Openscapes core team member and founding director
I am a marine ecologist working at the intersection of actionable science, data science, and open science. My main focus is mentoring teams to develop technical and leadership mindsets and skills for data-intensive research, grounded in climate solutions, inclusion, and kindness. I earned my PhD from Stanford University in 2012 studying drivers and impacts of Humboldt squid in a changing climate. In 2018 I founded Openscapes as an open source community following my own research team’s path to better science in less time, as a Mozilla Fellow and Senior Fellow at the National Center for Ecological Analysis and Synthesis (NCEAS) at the University of California Santa Barbara. In 2022 I started Openscapes LLC, a small woman-owned business to support the growing Openscapes open source community.
Devan Burke
Devan Burke (she/her) is an Analyst and Contract Manager at the Office of Information Management and Analysis (OIMA) at the State Water Resources Control Board, and an Instructor for[ Openscapes at the Water Boards](https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fcawaterboarddatacenter.github.io%2Fswrcb-openscapes%2F&data=05%7C02%7CDevan.Burke%40waterboards.ca.gov%7C1f1595535600426b1eef08dc23873ba3%7Cfe186a257d4941e6994105d2281d36c1%7C0%7C0%7C638424312429892822%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=tIHQvC018%2F%2FA7SlNT%2FelVg2rf3EDlEqeomvJYaiPJSA%3D&reserved=0). She holds a M.S. in Sustainability Science and Policy from Maastricht University, Netherlands and a B.A. in Global Studies from CSU Monterey Bay. Devan is passionate about making data and science more accessible, transparent and equitable by implementing team science through open science pathways. 
Anna Holder
Anna Holder (she,her) is the Open Data Science, Equity & Tribal Coordinator for the Office of Information Management and Analysis (OIMA) at the California State Water Resources Control Board, and the lead  for[ Openscapes at the Water Boards](https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fcawaterboarddatacenter.github.io%2Fswrcb-openscapes%2F&data=05%7C02%7CDevan.Burke%40waterboards.ca.gov%7C1f1595535600426b1eef08dc23873ba3%7Cfe186a257d4941e6994105d2281d36c1%7C0%7C0%7C638424312429892822%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=tIHQvC018%2F%2FA7SlNT%2FelVg2rf3EDlEqeomvJYaiPJSA%3D&reserved=0). Anna obtained her M.S. and B.S. from CSU Monterey Bay in Applied Marine and Watershed Science. Anna is working to put the principles of open science and equity into practice and helping others in the Water Boards and beyond to do the same. 

Stefanie Butland

Stefanie Butland (she,her) is a core Openscapes team member and co-leads Champions Cohorts. Stefanie holds an M.Sc. from York University, Toronto. She is a research scientist by training and an open science and tech community leader.

**Comment by jules32** [comment]
Slides: https://docs.google.com/presentation/d/1yOTdJcvWdVWSLIE72L4cCN2b22y-6ZDlOouqP1i_bSI/edit?usp=sharing

Developed more today and handed off to Anna live in the slides :)

**Comment by jules32** [comment]
Anna Holder, Devan Burke and I just presented about Openscapes and the Champions program to the California Department of Water Resources ([slides](https://docs.google.com/presentation/d/1yOTdJcvWdVWSLIE72L4cCN2b22y-6ZDlOouqP1i_bSI/edit#slide=id.g2c1dee5ed55_3_272)) - 136 participants! 

They are interested in potentially a Champions Cohort but certainly becoming more connected with the Water Boards (Anna & Devan's group). Great job Anna and Devan! I LOVE Devan's analogy of the messy kitchen - that has everything you need but it's just too much clutter and spills - and how professional kitchens take time to prep, clean, put things away, and that's what Openscapes helped her do (and using Allison Horst's artwork too! ❤ ) The Q&A felt really good too - I feel like I'm not great at Q&A but this felt good. I felt more collected co-answering with Anna and Devan (go team!) so worth noting:
- Q: How to help make cloud computing a thing at our org? A: "show not tell". screenshare, show a video, you don't need to be an expert to pass on your vision/ideas. This approach not limited to Cloud: specific example with [A Year of Open Science Community Building at NOAA Fisheries](https://www.youtube.com/watch?v=n1VaV8f6qQE&list=PLChfyH8TVDGnB_zDCm8d9oonMomfk8v9X&index=14).
- Q: How to automate reports when on a deadline? A: "coworking" synchronously, having a chance to screenshare on what works, handoffs, get ideas for improvement. Then, we've seen NOAA across teams create quarto templates (branding is the same across NOAA!) https://nmfs-opensci.github.io/ResourceBook/. 
  - Anna A: start with the figures, move that into a shared workflow, keep the text where it is, can't do it all at once, iterate and incorporate as you can. Different flavors of coworking: I also cowork with Devan when we're not working on the same thing, "joyful accountability". Our short publication co-authored with Openscapes Mentors across agencies focuses on coworking: [Shifting institutional culture to develop climate solutions with Open Science](https://doi.org/10.1002/ece3.11341).

136 participants! 

Kamyar Guivetchi recommendation: communities of practice
- [What is a community of practice](https://www.communityofpractice.ca/background/what-is-a-community-of-practice/)?
- [Introduction to communities of practice - wenger-trayner](https://www.wenger-trayner.com/introduction-to-communities-of-practice/) (2015)
- [CoP guidebook - wenger-trayner](https://www.wenger-trayner.com/cop-guidebook/) (2022)
- [Learning to make a difference - wenger-trayner](https://www.wenger-trayner.com/learning-to-make-a-difference-book/) (2020)
