### ISSUE TITLE
NASA PI Planning Plenary - Sept 10

### ISSUE THREAD

**Issue by jules32** [Openscapes/how_we_work#370]
30 mins, including Q&A. Plenary theme: Together We Innovate

**Comment by jules32** [comment]
**Title**: How Openscapes supports teams in open science: stories of how we work

**Abstract:** Openscapes is an open source approach and community that helps researchers and those supporting research find each other and feel empowered to conduct data-intensive science. We support open science as “kinder science for future us”: the vision is a scientific culture that is more efficient, more kind, and more collaborative, and that can uncover solutions faster together to the most pressing climate and social challenges. Our main activity is mentorship to build open source technical and collaborative leadership skills within and across teams and organizations, connecting groups and role-modeling open practices that are critical elements to helping shift towards open science. We often hear the question: “what does Open Science look like”? I’ll share examples and stories from the growing Openscapes community including NASA, NOAA, EPA, and Black in Marine Science that supports open science as a daily practice, and actionable ideas teams can take to join the open science movement.

**Bio**
Julia Stewart Lowndes, PhD
Openscapes core team member and founding director

I am a marine ecologist working at the intersection of actionable science, data science, and open science. My main focus is mentoring teams to develop technical and leadership mindsets and skills for data-intensive research, grounded in climate solutions, inclusion, and kindness. I earned my PhD from Stanford University in 2012 studying drivers and impacts of Humboldt squid in a changing climate. In 2018 I founded Openscapes as an open source community following my own research team’s path to better science in less time, as a Mozilla Fellow and Senior Fellow at the National Center for Ecological Analysis and Synthesis (NCEAS) at the University of California Santa Barbara. In 2022 I started Openscapes LLC, a small woman-owned business to support the growing Openscapes open source community.

**Comment by jules32** [comment]
New title, abstract and (draft!!) slides

**Title: Forking as a worldview**

**Abstract:** Forking is a concept from software development, which has evolved with open source software and the internet. Forking means taking something that works and is  made available, and adapting it to your own use, while being networked back to the source – this networking serves dual purposes of being able to contribute back and also to provide appropriate credit. Forking “something” has traditionally been code, but it can be applied to nearly anything. It is about taking something that works to new places to solve problems faster. Since 2018, Openscapes has been working with teams in government and academia to help upskill science teams to work on big collaborative challenges through open science. With NASA Openscapes, this big challenge is upskilling people that use NASA Earthdata to migrate their workflows to cloud computing, as NASA Earthdata holdings migrate to the cloud. We’ve supported this effort through developing a mentor community across NASA Earth science data centers (DAACs) to co-create common tutorials and develop skills for teaching, mentoring, facilitation. And, in the process, we’ve forked a lot of code, documentation, workshop setup, slides, art, teaching approaches, and even whole programs like NOAA Fisheries Openscapes and Pathways to Open Science. We’ve come to realize that forking is a way of thinking, a worldview. Forking is an important thing to call out as we think about how we innovate together through open science, and I'm excited to talk about it with you all!

**Comment by jules32** [comment]
Justin Rice spoke up afterwards underscoring how this is all a big achievement of collaboration across NASA HQ, ESDIS leadership, all the DAAC Managers and DAAC staff. Great to fork this and say this myself the next time.

Was really happy about how this went! Slack message: 

I just gave a plenary at an internal NASA meeting (240 people): [Forking as a Worldview: A big idea that frames Openscapes thinking](https://docs.google.com/presentation/d/1u0pQ3p3eNMxPn44GsZF0OKxhnJem7MD_3MWp8W_qXp8/edit#slide=id.g2f7acce46f8_0_0). I talked about forking as reusing what works in new places, with examples of earthaccess forking the open source software dev approach into government, and NASA Openscapes and then NOAA Fisheries Openscapes forking open source frameworks to tackle big challenges (cloud migration, data modernization). I shared what people can do to develop forking as a worldview through centering inclusion, and real challenges as individuals and orgs make these shifts. And, why it’s worth it: so we can tackle big challenges together and increase morale for teams doing this hard work. So much here from what the whole Openscapes community is doing, I wish we could call out every single example you do to celebrate! Kudos also to Liz Neeley (Liminal) and Maryam Zaringhalam (The White House, NIH National Libraries of Medicine), who reacted to the “forking” concept so much it inspired me to center a whole talk around it, and Erin Robinson – turns out, forking is the first step of the Openscapes Flywheel :)

**Comment by jules32** [comment]
Let's create an events page that we can point to:

Title: Plenary at internal NASA meeting: Together We Innovate
Subtitle: PI Planning, Fall 2024

Julie Lowndes gave a talk:

**Title**: Forking as a worldview

**Abstract**: Forking is a concept from software development, which has evolved with open source software and the internet. Forking means taking something that works and is made available, and adapting it to your own use, while being networked back to the source – this networking serves dual purposes of being able to contribute back and also to provide appropriate credit. Forking “something” has traditionally been code, but it can be applied to nearly anything. It is about taking something that works to new places to solve problems faster. Since 2018, Openscapes has been working with teams in government and academia to help upskill science teams to work on big collaborative challenges through open science. With NASA Openscapes, this big challenge is upskilling people that use NASA Earthdata to migrate their workflows to cloud computing, as NASA Earthdata holdings migrate to the cloud. We’ve supported this effort through developing a mentor community across NASA Earth science data centers (DAACs) to co-create common tutorials and develop skills for teaching, mentoring, facilitation. And, in the process, we’ve forked a lot of code, documentation, workshop setup, slides, art, teaching approaches, and even whole programs like NOAA Fisheries Openscapes and Pathways to Open Science. We’ve come to realize that forking is a way of thinking, a worldview. Forking is an important thing to call out as we think about how we innovate together through open science, and I'm excited to talk about it with you all!

Following the talk, she remarked [Slack message above]

**Comment by stefaniebutland** [comment]
Published:
https://openscapes.org/events/2024-09-10-nasa-pi-plenary/
https://nasa-openscapes.github.io/news/2024-09-10-nasa-pi-plenary/

**Comment by jules32** [comment]
See #387
