### ISSUE TITLE
Review NOAA Mentors Agendas

### ISSUE THREAD

**Issue by jules32** [Openscapes/how_we_work#372]
@stefaniebutland , please review [_Coworking [ nmfs-openscapes-mentors ]](https://docs.google.com/document/d/1voDfG3-sXwM0svmFu4OSebWpcBdbjIUtHUmNGtP8D7k/edit) (I have done the same). As you do, please: 

- [x] create a “blank/public copy” of this - remove all roll call and notes - but keep any lessons part (with an eye toward reusing/kyber some day) 
- [x] Add to https://nmfs-openscapes.github.io/mentors/mentor-calls
- [x] https://openscapes.github.io/approach-guide/mentors-framework/engage.html

We don't have a "Mentor Series" now, which is ok; not sure that is what we need. But in the meantime, these are places we'll look for this, and ok to have a little redundancy

**Comment by stefaniebutland** [comment]
blank agendas, set as View by anyone w link: [_CoworkingAgendas_2023-nmfs-openscapes-mentors [ public ]](https://docs.google.com/document/d/16F5nt0TNfU66OakTBmuyrZkASv9vKDMGkXjb_eJY_78/edit?tab=t.0#heading=h.edicpwdtfo20).

**Comment by stefaniebutland** [comment]
completed
