### ISSUE TITLE
NOAA Champions engagement

### ISSUE THREAD

**Issue by jules32** [Openscapes/how_we_work#373]
Stef and Julie to think through more together:

- [x] update info & nomination process https://nmfs-openscapes.github.io/champions.html 
- [x] email Mentors with above info
- [x] schedule brown bags, AMAs, etc

**Comment by jules32** [comment]
In progress - 

Today we: 

- [x] emailed mentors asking to help share the word and organize brown bags
- [x] updated nmfs-openscapes.github.io with champions, mentors, and overall info: https://github.com/nmfs-openscapes/nmfs-openscapes.github.io/pull/29

**Comment by stefaniebutland** [comment]
[NMFS Champions program page](https://nmfs-openscapes.github.io/champions.html) updated with brown bag sessions, cohort timeline image, teams description

Add ~3 examples from past individual & team participants
- [x] Kourtney Burger SWFSC
- [x] MML team video
- [x] excerpt from YOS recording

**Comment by jules32** [comment]
Woop, sent selection emails today
