### ISSUE TITLE
Buy more hex stickers

### ISSUE THREAD

**Issue by jules32** [Openscapes/how_we_work#374]
- [x] Buy to take in person to Posit & DC & Wyoming

- [x] Send to Anna B for PI Planning

**Comment by jules32** [comment]
Ordered, and updated in the Approach Guide
https://github.com/Openscapes/approach-guide/commit/d98701b93b6ae5998a64e0633aca01cfe0168793

**Comment by stefaniebutland** [comment]
I'll bring these to posit::conf 


![Image](https://github.com/user-attachments/assets/bd46c708-fe19-4b8c-abc4-752afe821583)

**Comment by jules32** [comment]
First time I ordered so many they shipped in a box!

![Image](https://github.com/user-attachments/assets/56aadafb-624d-48a3-a9ef-aecf71d94fe7)
