### ISSUE TITLE
Openscapes dinner social at posit::conf Wed Aug 14

### ISSUE THREAD

**Issue by stefaniebutland** [Openscapes/how_we_work#375]
**Openscapes Mentors & Champions!** Join us to connect over dinner /social Wednesday, August 14, 7:30 pm 

UPDATE: Let's meet at [Stoup Brewing - Capitol Hill](https://www.stoupbrewing.com/capitol-hill/), 1158 Broadway.
Apparently there will be a food truck outside, and you can order in your own food. Decided on this so people can come and go and hang out as long as we want.

We plan to walk over after the [posit::conf(2024) Community Mixer](https://www.meetup.com/rladies-seattle/events/300741695) that's hosted by R-Ladies and PyLadies and open to the public.

~[Ba Bar Vietnamese restaurant](https://babarseattle.com/south-lake-union/street-food/) South Lake Union (500 Terry Ave N, Seattle, WA 98109).~ No-host dinner & drinks - each person will pay their own way.
~Please RSVP for Openscapes dinner by commenting below. Stef will reserve a table.~

**Comment by jules32** [comment]
Yay! +1 for me please :)

**Comment by eeholmes** [comment]
+1 for Eli

**Comment by shospital** [comment]
I would love to connect but I will be flying out on Weds right after the conference. hope to catch you all at the conf!

**Comment by stefaniebutland** [comment]
updated location in top post. Now Stoup Brewing.

**Comment by stefaniebutland** [comment]
Was so great to connect and hang out with so many lovely folks ❤ 
Closing as completed
