### ISSUE TITLE
Book quarterly IED Huddles

### ISSUE THREAD

**Issue by jules32** [Openscapes/how_we_work#381]
From our Aug 20 Team Huddle: 

How we do inclusion + equity = diversity.
Based on discussion of Carpentries IDEAS Toolkit, we’ve booked a quarterly 1hr team huddle for ongoing discussion & continuous improvement

**Comment by jules32** [comment]
For Stef or Julie todo

**Comment by stefaniebutland** [comment]
done in Google Cal, with text in description - next one Nov 19 for 1hr

**Comment by jules32** [comment]
Thank you!
