### ISSUE TITLE
Add AGU to events pages

### ISSUE THREAD

**Issue by jules32** [Openscapes/how_we_work#388]
Hi @stefaniebutland , would you be able to do the following next week, coworking with @ateucher to share how we cross-post events so that he is also able to do this going forward. 

Note: as you go to do the following, please also update the 2024-agu-planning planning README with any AGU links (you may have to search the AGU schedule) for full author lists or whatever will make this more useful at-a-glance for Openscapes folks to find each other and amplify. Great also to share with NASA, NMFS, EPA leadership.

- [x] post on openscapes.org: an events page for AGU 2024. Something simple like what [we did this in 2022](https://openscapes.org/events/2022-12-13-agu-fall). Highlight that many talks/posters are with different agencies and cross-agencies. For most up-to-date information, see https://github.com/NASA-Openscapes/2024-agu-planning/. 
    - [x] to highlight/note: Monday posters: fledging poster is cross-NASA DAACs. py-rocket talk is NASA-NMFS-UCB. Solutions & Solvers talk is following White House visit and Challenge.gov
    - [x] to highlight: EPA has a talk
    - [x] to highlight: what else?
 - [x] cross-post on NASA
 - [x] cross-post on Pathways (Ileana is co-author on Solutions & Solvers)
 - [x] cross-post on NMFS (woo it's a thing!)

Thank you!

**Comment by stefaniebutland** [comment]
Ack! I just noticed this was for last week. Sorry about that. Arranging time asap to do with Andy.

**Comment by stefaniebutland** [comment]
past AGU events posted:

- December 10, 2023: Activities at the AGU Fall Meeting https://nasa-openscapes.github.io/news/2023-12-10-agu-fall-meeting/
- December 13, 2022: AGU: The Future is Open. Openscapes presentations at the American Geophysical Union (AGU) fall 2022 conference https://openscapes.org/events/2022-12-13-agu-fall/
- December 17, 2021: AGU: Open Science In Action. An innovation session at the American Geophysical Union (AGU) fall conference https://openscapes.org/events/2021-12-17-agu-open-science-in-action/
-

**Comment by stefaniebutland** [comment]
wip in PR https://github.com/Openscapes/website-new/pull/161

**Comment by stefaniebutland** [comment]
published https://openscapes.org/events/2024-12-09-agu-fall/

@jules32 let me know if you'd like any edits to event post.

**Comment by jules32** [comment]
Looks great, thank you Stef!

**Comment by stefaniebutland** [comment]
I will
- [x] Slack general & share link in nasa-mentors
- [x] NMFS Google Space Mentors
- [x] email EPA team
- [x] post to bluesky, mastodon
- [x] review repo README cf AGU schedule

**Comment by stefaniebutland** [comment]
@jules32 Is this ok to close now?
I did not add full author lists to README since they are available at the AGU links listed, and the author lists are long. Added 
> Expanding a talk or poster item below reveals an AGU link for full author list, abstract, time, and location.

**Comment by jules32** [comment]
Yes, sounds good. Thanks!
