### ISSUE TITLE
ESA conference submission - by Dec 3

### ISSUE THREAD

**Issue by jules32** [Openscapes/how_we_work#397]
European Space Agency (ESA)

LIVING PLANET SYMPOSIUM

23—27 JUNE 2025

VIENNA, AUSTRIA

Tutorials starting 22 June PM

https://lps25.esa.int/#w-node-_0488106f-ce92-9b7b-01c3-8ad75f3f5e36-489f4c31

**Comment by jules32** [comment]
Submitted to Theme D. Digital Innovation and Green Solutions

Sub Theme 03 Open Science and Open Innovation

Title D.03.01 Harnessing Open and Community-Driven Innovation in Times of Emergencies

Convenors: Claudia Vitolo (ESA); Loretta Latronico (ESA); Uta Wehn (IHE Delft); Angelo Cavallo (Polimi)

## Submission

**Title:** Forking as a worldview: a software engineering concept transforming government agencies IRL (in real life) with Openscapes

**Abstract:** “Forking” is a term from software development that describes taking something that is working well and adapting it for new uses. Critically, the work is also networked back to the source so we can credit and contribute as we build momentum together and solve problems faster. Forking “something” has traditionally been executable code, but it can be applied to nearly anything. Since 2018, Openscapes, as an open source approach and movement, has been working with teams in government and academia to help upskill science teams to work on big collaborative challenges through open science. With NASA Openscapes, this big challenge is upskilling people that use NASA Earthdata to migrate their workflows to the cloud, as NASA Earthdata holdings migrate to the cloud. We’ve supported this effort through developing a Mentor community across NASA Earth science data centers (DAACs, co-led by Erin Robinson, Metadata Game Changers) to co-create common tutorials and develop skills for teaching, mentoring, facilitation. And, in the process, we’ve forked a lot of code, documentation, workshop setup, slides, art, teaching approaches, to name a few.

One outstanding example of forking is `earthaccess`, a python library to search, download or stream NASA Earth science data with a few lines of code. `earthaccess` has been nothing short of game-changing for the user experience, changing a workflow from 20+ lines of terminal code and clicking out to hidden files and authentication to 4 lines of python code. Its creation was motivated through recurring workshops working closely with researchers, as  NASA Openscapes Mentors saw the need to provide easy to use tools for researchers to access data programmatically. These Mentors collaborated to design and develop `earthaccess`, led by Luis López (NASA NSIDC). Now, there are many contributors across NASA, as well as researchers and open source developers contributing via biweekly hackdays! There is now also an R complement: `earthdatalogin` by Carl Boettiger (University of California Berkeley and rOpenSci). This is a story of open source software development approaches being forked within federal government.

Forking examples also includes whole programs – such as NOAA Fisheries Openscapes tackling data modernization and upskilling and the workforce (co-led by Eli Holmes, NOAA Fisheries), and Pathways to Open Science program building community for Black marine and environmental scientists (led by Ileana Fenwick, Openscapes). We’ve also forked the idea of coworking together syncronously and asynchronous on an Open Access editorial written collaboratively by mentors across the Openscapes community: "Shifting institutional culture to develop climate solutions with Open Science". From co-author Anna Holder, California EPA / Water Boards: “It’s a short read and quite uplifting and inspirational and provides some more insight and what we’re learning as we implement Openscapes across organizations.”

We’ve come to realize that forking is a way of thinking, a worldview. Forking is an important thing to call out as we think about how we innovate together through open science within and across boundaries, in the face of cascading and compounding emergencies. This work is by the growing Openscapes community and people working every day for kinder science for future us, and I'm excited to have the chance to share more with you all!

Links: 
Openscapes: https://openscapes.org/
Earthaccess: https://nsidc.github.io/earthaccess 
Earthdatalogin: https://cran.r-project.org/web/packages/earthdatalogin/ 
NASA Openscapes: https://nasa-openscapes.github.io/ 
NOAA Fisheries Openscapes: https://nmfs-openscapes.github.io/ 
Pathways to Open Science: https://openscapes.github.io/pathways-to-open-science 
Shifting institutional culture to develop climate solutions with Open Science (Lowndes et al 2024, Ecology and Evolution, 14, e11341.[ https://doi.org/10.1002/ece3.11341](https://doi.org/10.1002/ece3.11341)

**Comment by stefaniebutland** [comment]
memory jog @jules32: Claudia Vitolo (ESA session convener) was at rOpenSci [unconf17](https://unconf17.ropensci.org/)

**Comment by jules32** [comment]
Oh that is how I know Claudia! I was thinking it was through RLadies :) Thanks Stef!
