### ISSUE TITLE
Fred Hutch first planning call

### ISSUE THREAD

**Issue by jules32** [Openscapes/how_we_work#398]

**Comment by jules32** [comment]
Hi @stefaniebutland ! Sean is going to invite us to a planning call next Tuesday; would you be able to make a copy of the [Openscapes-CohortPlanningDoc](https://docs.google.com/document/d/1uzQ-hic0Kn0pNyeb9VwVNDwMYRetZgiXkQ2mZIe_TXk/edit?usp=sharing) doc before then? There are new team members so I/we can plan to share more from https://openscapes.github.io/approach-guide/champions/design.html as needed :) Thank you!

**Comment by stefaniebutland** [comment]
Will do!

**Comment by stefaniebutland** [comment]
Hi @jules32 ! I've made 2025- and 2023-fred-hutch folders inside [FredHutch-Openscapes-CohortPlanning](https://drive.google.com/drive/folders/11m8AuPEiPkUNja_7MERT2PE2eJfqHr7I?usp=drive_link). CohortPlanning doc and CohortCalendaring sheet created with basic updates.
Spot for Dec 10 meeting ready to go

**Comment by stefaniebutland** [comment]
closing as completed
