### ISSUE TITLE
Tara Community Call followup

### ISSUE THREAD

**Issue by jules32** [Openscapes/how_we_work#9]
- [x] upload video to [GDrive](https://drive.google.com/drive/folders/17KQ3gJ56YOERKaenWLly5XfH9cXL-c8u?usp=sharing) @erinmr
- [x] put on youtube @jules32
- [x] create mini blog post: just links and as a pointer to the youtube video
- [ ] send out as email @erinmr
- [x] post on blog @jules32
- [x] update events page with links @jules32 
- [x] Tweet! @jules32

**Comment by erinmr** [comment]
Drafted email/blog post here -> https://docs.google.com/document/d/14pc9rqyQnj42fatOcdGRkl55mft0mBNDYiC-rAU3g4k/edit Edit away!

**Comment by jules32** [comment]
Amazing @erinmr, will do!

**Comment by jules32** [comment]
Hi @erinmr, the video is live here: https://youtu.be/XQMgyLuKwsI

I've completed edits, all set for an email and I'll post on the blog.

**Comment by erinmr** [comment]
Here is email list for attendees: https://docs.google.com/spreadsheets/d/1WTai1kxgeGwZkbGivAHjAspZG0OB-ngF/edit#gid=862508308

**Comment by erinmr** [comment]
Great work!
